In [1]:
import pandas as pd
import numpy as np

In [2]:
matches = pd.read_csv('IPL Matches 2008-2020.csv', index_col = 'id')
matches.head()

,city,date,player_of_match,venue,neutral_venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,eliminator,method,umpire1,umpire2
id,,,,,,,,,,,,,,,,
335982,Bangalore,2008-04-18,BB McCullum,M Chinnaswamy Stadium,0,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,N,NaN,Asad Rauf,RE Koertzen
335983,Chandigarh,2008-04-19,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",0,Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,N,NaN,MR Benson,SL Shastri
335984,Delhi,2008-04-19,MF Maharoof,Feroz Shah Kotla,0,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,N,NaN,Aleem Dar,GA Pratapkumar
335985,Mumbai,2008-04-20,MV Boucher,Wankhede Stadium,0,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,N,NaN,SJ Davis,DJ Harper
335986,Kolkata,2008-04-20,DJ Hussey,Eden Gardens,0,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,N,NaN,BF Bowden,K Hariharan

In [3]:
import datetime 
matches.date = pd.to_datetime(matches.date)
matches = matches[matches.date > np.datetime64('2018-01-01')]

In [4]:
delivery = pd.read_csv('IPL Ball-by-Ball 2008-2020.csv', index_col = 'id')
delivery.head()
delivery = delivery.loc[matches.index]
delivery.batting_team[delivery.batting_team == 'Delhi Daredevils'] = 'Delhi Capitals'
delivery.bowling_team[delivery.bowling_team == 'Delhi Daredevils'] = 'Delhi Capitals'
delivery

<ipython-input-4-6219481fab41>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  delivery.batting_team[delivery.batting_team == 'Delhi Daredevils'] = 'Delhi Capitals'
<ipython-input-4-6219481fab41>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  delivery.bowling_team[delivery.bowling_team == 'Delhi Daredevils'] = 'Delhi Capitals'

,inning,over,ball,batsman,non_striker,bowler,batsman_runs,extra_runs,total_runs,non_boundary,is_wicket,dismissal_kind,player_dismissed,fielder,extras_type,batting_team,bowling_team
id,,,,,,,,,,,,,,,,,
1136561,1,7,2,Ishan Kishan,SA Yadav,RA Jadeja,4,0,4,0,0,NaN,NaN,NaN,NaN,Mumbai Indians,Chennai Super Kings
1136561,1,7,3,Ishan Kishan,SA Yadav,RA Jadeja,0,0,0,0,0,NaN,NaN,NaN,NaN,Mumbai Indians,Chennai Super Kings
1136561,1,7,4,Ishan Kishan,SA Yadav,RA Jadeja,0,0,0,0,0,NaN,NaN,NaN,NaN,Mumbai Indians,Chennai Super Kings
1136561,1,7,5,Ishan Kishan,SA Yadav,RA Jadeja,4,0,4,0,0,NaN,NaN,NaN,NaN,Mumbai Indians,Chennai Super Kings
1136561,1,7,6,Ishan Kishan,SA Yadav,RA Jadeja,0,0,0,0,0,NaN,NaN,NaN,NaN,Mumbai Indians,Chennai Super Kings
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1237181,1,12,5,RR Pant,SS Iyer,NM Coulter-Nile,0,0,0,0,0,NaN,NaN,NaN,NaN,Delhi Capitals,Mumbai Indians
1237181,1,12,6,RR Pant,SS Iyer,NM Coulter-Nile,1,0,1,0,0,NaN,NaN,NaN,NaN,Delhi Capitals,Mumbai Indians
1237181,1,13,1,RR Pant,SS Iyer,KH Pandya,0,1,1,0,0,NaN,NaN,NaN,wides,Delhi Capitals,Mumbai Indians
1237181,1,13,2,RR Pant,SS Iyer,KH Pandya,1,0,1,0,0,NaN,NaN,NaN,NaN,Delhi Capitals,Mumbai Indians
1237181,1,13,3,SS Iyer,RR Pant,KH Pandya,1,0,1,0,0,NaN,NaN,NaN,NaN,Delhi Capitals,Mumbai Indians

In [5]:
matches.team1[matches.team1 == 'Delhi Daredevils'] = 'Delhi Capitals'
matches.team2[matches.team2 == 'Delhi Daredevils'] = 'Delhi Capitals'
matches.winner[matches.winner == 'Delhi Daredevils'] = 'Delhi Capitals'
matches.head()

,city,date,player_of_match,venue,neutral_venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,eliminator,method,umpire1,umpire2
id,,,,,,,,,,,,,,,,
1136561,Mumbai,2018-04-07,DJ Bravo,Wankhede Stadium,0,Mumbai Indians,Chennai Super Kings,Chennai Super Kings,field,Chennai Super Kings,wickets,1.0,N,NaN,CB Gaffaney,A Nand Kishore
1136562,Chandigarh,2018-04-08,KL Rahul,"Punjab Cricket Association IS Bindra Stadium, ...",0,Kings XI Punjab,Delhi Capitals,Kings XI Punjab,field,Kings XI Punjab,wickets,6.0,N,NaN,KN Ananthapadmanabhan,RJ Tucker
1136563,Kolkata,2018-04-08,SP Narine,Eden Gardens,0,Kolkata Knight Riders,Royal Challengers Bangalore,Kolkata Knight Riders,field,Kolkata Knight Riders,wickets,4.0,N,NaN,C Shamshuddin,A Deshmukh
1136564,Hyderabad,2018-04-09,S Dhawan,"Rajiv Gandhi International Stadium, Uppal",0,Sunrisers Hyderabad,Rajasthan Royals,Sunrisers Hyderabad,field,Sunrisers Hyderabad,wickets,9.0,N,NaN,VA Kulkarni,NJ Llong
1136565,Chennai,2018-04-10,SW Billings,"MA Chidambaram Stadium, Chepauk",0,Chennai Super Kings,Kolkata Knight Riders,Chennai Super Kings,field,Chennai Super Kings,wickets,5.0,N,NaN,CB Gaffaney,AK Chaudhary

In [6]:
matches['Team1Won'] = matches.team1 == matches.winner
matches['Team2Won'] = matches.team2 == matches.winner

In [7]:
game_lineups = list(zip(list(matches['team1']), list(matches['team2'])))
games = []
for game in game_lineups:
    games.append('_'.join(sorted(game)))

matches['team_team'] = games

In [8]:
matches[['team_team', 'winner']]

,team_team,winner
id,,
1136561,Chennai Super Kings_Mumbai Indians,Chennai Super Kings
1136562,Delhi Capitals_Kings XI Punjab,Kings XI Punjab
1136563,Kolkata Knight Riders_Royal Challengers Bangalore,Kolkata Knight Riders
1136564,Rajasthan Royals_Sunrisers Hyderabad,Sunrisers Hyderabad
1136565,Chennai Super Kings_Kolkata Knight Riders,Chennai Super Kings
...,...,...
1216547,Mumbai Indians_Royal Challengers Bangalore,Royal Challengers Bangalore
1237177,Delhi Capitals_Mumbai Indians,Mumbai Indians
1237178,Royal Challengers Bangalore_Sunrisers Hyderabad,Sunrisers Hyderabad
1237180,Delhi Capitals_Sunrisers Hyderabad,Delhi Capitals
1237181,Delhi Capitals_Mumbai Indians,Mumbai Indians

In [9]:
result = []
for i in range(len(matches)):
    result.append(list(matches['team_team'].str.split('_'))[i][0] == matches['winner'].iloc[i])
matches['result'] = result
matches

,city,date,player_of_match,venue,neutral_venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,eliminator,method,umpire1,umpire2,Team1Won,Team2Won,team_team
id,,,,,,,,,,,,,,,,,,,
1136561,Mumbai,2018-04-07,DJ Bravo,Wankhede Stadium,0,Mumbai Indians,Chennai Super Kings,Chennai Super Kings,field,Chennai Super Kings,True,1.0,N,NaN,CB Gaffaney,A Nand Kishore,False,True,Chennai Super Kings_Mumbai Indians
1136562,Chandigarh,2018-04-08,KL Rahul,"Punjab Cricket Association IS Bindra Stadium, ...",0,Kings XI Punjab,Delhi Capitals,Kings XI Punjab,field,Kings XI Punjab,False,6.0,N,NaN,KN Ananthapadmanabhan,RJ Tucker,True,False,Delhi Capitals_Kings XI Punjab
1136563,Kolkata,2018-04-08,SP Narine,Eden Gardens,0,Kolkata Knight Riders,Royal Challengers Bangalore,Kolkata Knight Riders,field,Kolkata Knight Riders,True,4.0,N,NaN,C Shamshuddin,A Deshmukh,True,False,Kolkata Knight Riders_Royal Challengers Bangalore
1136564,Hyderabad,2018-04-09,S Dhawan,"Rajiv Gandhi International Stadium, Uppal",0,Sunrisers Hyderabad,Rajasthan Royals,Sunrisers Hyderabad,field,Sunrisers Hyderabad,False,9.0,N,NaN,VA Kulkarni,NJ Llong,True,False,Rajasthan Royals_Sunrisers Hyderabad
1136565,Chennai,2018-04-10,SW Billings,"MA Chidambaram Stadium, Chepauk",0,Chennai Super Kings,Kolkata Knight Riders,Chennai Super Kings,field,Chennai Super Kings,True,5.0,N,NaN,CB Gaffaney,AK Chaudhary,True,False,Chennai Super Kings_Kolkata Knight Riders
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1216547,Dubai,2020-09-28,AB de Villiers,Dubai International Cricket Stadium,0,Royal Challengers Bangalore,Mumbai Indians,Mumbai Indians,field,Royal Challengers Bangalore,False,NaN,Y,NaN,Nitin Menon,PR Reiffel,True,False,Mumbai Indians_Royal Challengers Bangalore
1237177,Dubai,2020-11-05,JJ Bumrah,Dubai International Cricket Stadium,0,Mumbai Indians,Delhi Capitals,Delhi Capitals,field,Mumbai Indians,False,57.0,N,NaN,CB Gaffaney,Nitin Menon,True,False,Delhi Capitals_Mumbai Indians
1237178,Abu Dhabi,2020-11-06,KS Williamson,Sheikh Zayed Stadium,0,Royal Challengers Bangalore,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Sunrisers Hyderabad,False,6.0,N,NaN,PR Reiffel,S Ravi,False,True,Royal Challengers Bangalore_Sunrisers Hyderabad
1237180,Abu Dhabi,2020-11-08,MP Stoinis,Sheikh Zayed Stadium,0,Delhi Capitals,Sunrisers Hyderabad,Delhi Capitals,bat,Delhi Capitals,True,17.0,N,NaN,PR Reiffel,S Ravi,True,False,Delhi Capitals_Sunrisers Hyderabad
1237181,Dubai,2020-11-10,TA Boult,Dubai International Cricket Stadium,0,Delhi Capitals,Mumbai Indians,Delhi Capitals,bat,Mumbai Indians,False,5.0,N,NaN,CB Gaffaney,Nitin Menon,False,True,Delhi Capitals_Mumbai Indians

In [10]:
matches.sort_values(by = 'date', inplace = True)

In [11]:
matches.tail()

,city,date,player_of_match,venue,neutral_venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,eliminator,method,umpire1,umpire2,Team1Won,Team2Won,team_team
id,,,,,,,,,,,,,,,,,,,
1216495,Sharjah,2020-11-03,S Nadeem,Sharjah Cricket Stadium,0,Mumbai Indians,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Sunrisers Hyderabad,False,10.0,N,NaN,C Shamshuddin,RK Illingworth,False,True,Mumbai Indians_Sunrisers Hyderabad
1237177,Dubai,2020-11-05,JJ Bumrah,Dubai International Cricket Stadium,0,Mumbai Indians,Delhi Capitals,Delhi Capitals,field,Mumbai Indians,False,57.0,N,NaN,CB Gaffaney,Nitin Menon,True,False,Delhi Capitals_Mumbai Indians
1237178,Abu Dhabi,2020-11-06,KS Williamson,Sheikh Zayed Stadium,0,Royal Challengers Bangalore,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Sunrisers Hyderabad,False,6.0,N,NaN,PR Reiffel,S Ravi,False,True,Royal Challengers Bangalore_Sunrisers Hyderabad
1237180,Abu Dhabi,2020-11-08,MP Stoinis,Sheikh Zayed Stadium,0,Delhi Capitals,Sunrisers Hyderabad,Delhi Capitals,bat,Delhi Capitals,True,17.0,N,NaN,PR Reiffel,S Ravi,True,False,Delhi Capitals_Sunrisers Hyderabad
1237181,Dubai,2020-11-10,TA Boult,Dubai International Cricket Stadium,0,Delhi Capitals,Mumbai Indians,Delhi Capitals,bat,Mumbai Indians,False,5.0,N,NaN,CB Gaffaney,Nitin Menon,False,True,Delhi Capitals_Mumbai Indians

In [12]:
overall_record = pd.DataFrame(columns = ['Games Won', 'Games Played'], index = np.arange(8))
overall_record.index = matches.groupby('team1').aggregate({'Team1Won' : 'sum'}).index
overall_record['Games Won'] = matches.groupby('team1').aggregate({'Team1Won' : 'sum'}).values.reshape(-1,1)
overall_record['Games Played'] = matches.groupby('team1').aggregate({'Team1Won' : 'count'}).values.reshape(-1,1)
overall_record

                             Games Won  Games Played
team1
Chennai Super Kings                 15            20
Delhi Capitals                      16            26
Kings XI Punjab                     11            20
Kolkata Knight Riders               14            26
Mumbai Indians                      15            25
Rajasthan Royals                     9            18
Royal Challengers Bangalore         11            24
Sunrisers Hyderabad                 14            21

In [13]:
overall_record['Games2 Won'] = matches.groupby('team2').aggregate({'Team2Won' : 'sum'}).values.reshape(-1,1)
overall_record['Games2 Played'] = matches.groupby('team2').aggregate({'Team2Won' : 'count'}).values.reshape(-1,1)

In [14]:
overall_record['Won'] = overall_record['Games2 Won'] + overall_record['Games Won']
overall_record['Played'] = overall_record['Games2 Played'] + overall_record['Games Played']
overall_record.drop(overall_record.columns[:4], axis = 1, inplace = True)
overall_record

                             Won  Played
team1
Chennai Super Kings           27      47
Delhi Capitals                24      47
Kings XI Punjab               18      42
Kolkata Knight Riders         22      44
Mumbai Indians                28      46
Rajasthan Royals              18      43
Royal Challengers Bangalore   18      43
Sunrisers Hyderabad           24      48

In [15]:
overall_record['Percentage'] = overall_record['Won'] / overall_record['Played']
overall_record

                             Won  Played  Percentage
team1
Chennai Super Kings           27      47    0.574468
Delhi Capitals                24      47    0.510638
Kings XI Punjab               18      42    0.428571
Kolkata Knight Riders         22      44    0.500000
Mumbai Indians                28      46    0.608696
Rajasthan Royals              18      43    0.418605
Royal Challengers Bangalore   18      43    0.418605
Sunrisers Hyderabad           24      48    0.500000

In [16]:
h2h = matches.groupby('team_team')['result'].mean()
h2h

team_team
Chennai Super Kings_Delhi Capitals                   0.571429
Chennai Super Kings_Kings XI Punjab                  0.666667
Chennai Super Kings_Kolkata Knight Riders            0.666667
Chennai Super Kings_Mumbai Indians                   0.250000
Chennai Super Kings_Rajasthan Royals                 0.500000
Chennai Super Kings_Royal Challengers Bangalore      0.666667
Chennai Super Kings_Sunrisers Hyderabad              0.750000
Delhi Capitals_Kings XI Punjab                       0.333333
Delhi Capitals_Kolkata Knight Riders                 0.666667
Delhi Capitals_Mumbai Indians                        0.375000
Delhi Capitals_Rajasthan Royals                      0.833333
Delhi Capitals_Royal Challengers Bangalore           0.666667
Delhi Capitals_Sunrisers Hyderabad                   0.375000
Kings XI Punjab_Kolkata Knight Riders                0.333333
Kings XI Punjab_Mumbai Indians                       0.333333
Kings XI Punjab_Rajasthan Royals                     0.500000
Kings XI Punjab_Royal Challengers Bangalore          0.333333
Kings XI Punjab_Sunrisers Hyderabad                  0.500000
Kolkata Knight Riders_Mumbai Indians                 0.166667
Kolkata Knight Riders_Rajasthan Royals               0.857143
Kolkata Knight Riders_Royal Challengers Bangalore    0.500000
Kolkata Knight Riders_Sunrisers Hyderabad            0.571429
Mumbai Indians_Rajasthan Royals                      0.166667
Mumbai Indians_Royal Challengers Bangalore           0.666667
Mumbai Indians_Sunrisers Hyderabad                   0.500000
Rajasthan Royals_Royal Challengers Bangalore         0.500000
Rajasthan Royals_Sunrisers Hyderabad                 0.333333
Royal Challengers Bangalore_Sunrisers Hyderabad      0.428571
Name: result, dtype: float64

In [17]:
delivery = delivery.loc[matches.index]

In [18]:
def over_type(x):
    if x <= 5:
        return 'Powerplay'
    elif x <= 15:
        return 'Middle'
    else:
        return 'Death'
delivery['Type of Over'] = delivery['over'].apply(lambda x: over_type(x))

In [19]:
delivery

,inning,over,ball,batsman,non_striker,bowler,batsman_runs,extra_runs,total_runs,non_boundary,is_wicket,dismissal_kind,player_dismissed,fielder,extras_type,batting_team,bowling_team,Type of Over
id,,,,,,,,,,,,,,,,,,
1136561,1,7,2,Ishan Kishan,SA Yadav,RA Jadeja,4,0,4,0,0,NaN,NaN,NaN,NaN,Mumbai Indians,Chennai Super Kings,Middle
1136561,1,7,3,Ishan Kishan,SA Yadav,RA Jadeja,0,0,0,0,0,NaN,NaN,NaN,NaN,Mumbai Indians,Chennai Super Kings,Middle
1136561,1,7,4,Ishan Kishan,SA Yadav,RA Jadeja,0,0,0,0,0,NaN,NaN,NaN,NaN,Mumbai Indians,Chennai Super Kings,Middle
1136561,1,7,5,Ishan Kishan,SA Yadav,RA Jadeja,4,0,4,0,0,NaN,NaN,NaN,NaN,Mumbai Indians,Chennai Super Kings,Middle
1136561,1,7,6,Ishan Kishan,SA Yadav,RA Jadeja,0,0,0,0,0,NaN,NaN,NaN,NaN,Mumbai Indians,Chennai Super Kings,Middle
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1237181,1,12,5,RR Pant,SS Iyer,NM Coulter-Nile,0,0,0,0,0,NaN,NaN,NaN,NaN,Delhi Capitals,Mumbai Indians,Middle
1237181,1,12,6,RR Pant,SS Iyer,NM Coulter-Nile,1,0,1,0,0,NaN,NaN,NaN,NaN,Delhi Capitals,Mumbai Indians,Middle
1237181,1,13,1,RR Pant,SS Iyer,KH Pandya,0,1,1,0,0,NaN,NaN,NaN,wides,Delhi Capitals,Mumbai Indians,Middle
1237181,1,13,2,RR Pant,SS Iyer,KH Pandya,1,0,1,0,0,NaN,NaN,NaN,NaN,Delhi Capitals,Mumbai Indians,Middle
1237181,1,13,3,SS Iyer,RR Pant,KH Pandya,1,0,1,0,0,NaN,NaN,NaN,NaN,Delhi Capitals,Mumbai Indians,Middle

In [20]:
run_rate_batting = delivery.groupby(['batting_team', 'Type of Over'])['total_runs'].mean() * 6
run_rate_bowling = delivery.groupby(['bowling_team', 'Type of Over'])['total_runs'].mean() * 6

In [21]:
run_rate_batting

batting_team                 Type of Over
Chennai Super Kings          Death           10.465779
                             Middle           7.396304
                             Powerplay        7.053118
Delhi Capitals               Death            9.974708
                             Middle           7.786017
                             Powerplay        7.735849
Kings XI Punjab              Death            9.424865
                             Middle           8.060086
                             Powerplay        8.038685
Kolkata Knight Riders        Death           10.450844
                             Middle           7.866962
                             Powerplay        7.908923
Mumbai Indians               Death           10.788293
                             Middle           7.857041
                             Powerplay        7.984751
Rajasthan Royals             Death            9.548458
                             Middle           7.641245
                             Powerplay        8.074873
Royal Challengers Bangalore  Death           10.224622
                             Middle           7.455917
                             Powerplay        7.898496
Sunrisers Hyderabad          Death            8.994152
                             Middle           7.586020
                             Powerplay        8.110988
Name: total_runs, dtype: float64

In [22]:
run_rate_bowling

bowling_team                 Type of Over
Chennai Super Kings          Death            9.784615
                             Middle           7.450939
                             Powerplay        7.534247
Delhi Capitals               Death            9.182257
                             Middle           7.901879
                             Powerplay        8.220035
Kings XI Punjab              Death           10.769394
                             Middle           7.781946
                             Powerplay        8.249047
Kolkata Knight Riders        Death           10.267974
                             Middle           8.177879
                             Powerplay        8.123699
Mumbai Indians               Death            9.269531
                             Middle           7.602797
                             Powerplay        7.501767
Rajasthan Royals             Death           11.027027
                             Middle           7.914388
                             Powerplay        8.005006
Royal Challengers Bangalore  Death           10.673751
                             Middle           7.563707
                             Powerplay        7.815889
Sunrisers Hyderabad          Death            9.335740
                             Middle           7.301868
                             Powerplay        7.384615
Name: total_runs, dtype: float64

In [23]:
runs_scored = delivery.reset_index().groupby(['batting_team', 'bowling_team']).aggregate({'total_runs': 'sum', 'id' : 'nunique'})
runs_scored['avg_runs'] = runs_scored['total_runs'] / runs_scored['id']
runs_scored.drop(['total_runs', 'id'], axis = 1, inplace = True)
runs = runs_scored.unstack()
runs = runs.stack()

In [24]:
wickets_taken = delivery.reset_index().groupby(['batting_team', 'bowling_team']).aggregate({'is_wicket': 'sum', 'id' : 'nunique'})
wickets_taken['avg_wickets'] = wickets_taken['is_wicket'] / wickets_taken['id']
wickets = wickets_taken['avg_wickets'].unstack()
wickets = wickets.stack()

In [25]:
delivery['is_boundary'] = np.isin(delivery['batsman_runs'], [4,6])

In [26]:
boundaries = delivery.groupby(['batting_team', 'bowling_team'])['is_boundary'].mean()
boundaries

batting_team                 bowling_team
Chennai Super Kings          Delhi Capitals                 0.163934
                             Kings XI Punjab                0.167813
                             Kolkata Knight Riders          0.173370
                             Mumbai Indians                 0.135714
                             Rajasthan Royals               0.162019
                             Royal Challengers Bangalore    0.139437
                             Sunrisers Hyderabad            0.178980
Delhi Capitals               Chennai Super Kings            0.162515
                             Kings XI Punjab                0.145527
                             Kolkata Knight Riders          0.207439
                             Mumbai Indians                 0.160768
                             Rajasthan Royals               0.188312
                             Royal Challengers Bangalore    0.183060
                             Sunrisers Hyderabad            0.152905
Kings XI Punjab              Chennai Super Kings            0.162534
                             Delhi Capitals                 0.163912
                             Kolkata Knight Riders          0.204444
                             Mumbai Indians                 0.169583
                             Rajasthan Royals               0.177658
                             Royal Challengers Bangalore    0.178121
                             Sunrisers Hyderabad            0.137447
Kolkata Knight Riders        Chennai Super Kings            0.181943
                             Delhi Capitals                 0.209396
                             Kings XI Punjab                0.218453
                             Mumbai Indians                 0.176230
                             Rajasthan Royals               0.194067
                             Royal Challengers Bangalore    0.167794
                             Sunrisers Hyderabad            0.170414
Mumbai Indians               Chennai Super Kings            0.168285
                             Delhi Capitals                 0.186096
                             Kings XI Punjab                0.198917
                             Kolkata Knight Riders          0.209402
                             Rajasthan Royals               0.178667
                             Royal Challengers Bangalore    0.189840
                             Sunrisers Hyderabad            0.158184
Rajasthan Royals             Chennai Super Kings            0.156727
                             Delhi Capitals                 0.156433
                             Kings XI Punjab                0.178177
                             Kolkata Knight Riders          0.144706
                             Mumbai Indians                 0.193687
                             Royal Challengers Bangalore    0.171561
                             Sunrisers Hyderabad            0.139535
Royal Challengers Bangalore  Chennai Super Kings            0.124829
                             Delhi Capitals                 0.153103
                             Kings XI Punjab                0.178571
                             Kolkata Knight Riders          0.192034
                             Mumbai Indians                 0.185889
                             Rajasthan Royals               0.169014
                             Sunrisers Hyderabad            0.142526
Sunrisers Hyderabad          Chennai Super Kings            0.155713
                             Delhi Capitals                 0.157895
                             Kings XI Punjab                0.136605
                             Kolkata Knight Riders          0.158654
                             Mumbai Indians                 0.143466
                             Rajasthan Royals               0.160229
                             Royal Challengers Bangalore    0.173913
Name: is_boundary, dtype: float64

In [27]:
delivery.dismissal_kind.value_counts()

caught                   1376
bowled                    321
run out                   142
lbw                       117
caught and bowled          58
stumped                    51
hit wicket                  3
retired hurt                2
obstructing the field       1
Name: dismissal_kind, dtype: int64

In [28]:
dismissal = pd.get_dummies(delivery[['batting_team', 'bowling_team', 'dismissal_kind']].loc[delivery.is_wicket == 1], columns= ['dismissal_kind']).groupby(
['batting_team', 'bowling_team']).mean()

dismissal = dismissal.drop(['dismissal_kind_obstructing the field', 'dismissal_kind_hit wicket', 'dismissal_kind_retired hurt'], axis =1)

In [29]:
dismissal

                                                         dismissal_kind_bowled  \
batting_team                bowling_team
Chennai Super Kings         Delhi Capitals                            0.090909
                            Kings XI Punjab                           0.263158
                            Kolkata Knight Riders                     0.222222
                            Mumbai Indians                            0.052632
                            Rajasthan Royals                          0.161290
                            Royal Challengers Bangalore               0.300000
                            Sunrisers Hyderabad                       0.228571
Delhi Capitals              Chennai Super Kings                       0.162791
                            Kings XI Punjab                           0.255814
                            Kolkata Knight Riders                     0.166667
                            Mumbai Indians                            0.180000
                            Rajasthan Royals                          0.058824
                            Royal Challengers Bangalore               0.178571
                            Sunrisers Hyderabad                       0.132075
Kings XI Punjab             Chennai Super Kings                       0.166667
                            Delhi Capitals                            0.146341
                            Kolkata Knight Riders                     0.192308
                            Mumbai Indians                            0.161290
                            Rajasthan Royals                          0.148148
                            Royal Challengers Bangalore               0.166667
                            Sunrisers Hyderabad                       0.142857
Kolkata Knight Riders       Chennai Super Kings                       0.071429
                            Delhi Capitals                            0.191489
                            Kings XI Punjab                           0.142857
                            Mumbai Indians                            0.051282
                            Rajasthan Royals                          0.114286
                            Royal Challengers Bangalore               0.184211
                            Sunrisers Hyderabad                       0.142857
Mumbai Indians              Chennai Super Kings                       0.083333
                            Delhi Capitals                            0.127660
                            Kings XI Punjab                           0.166667
                            Kolkata Knight Riders                     0.040000
                            Rajasthan Royals                          0.218750
                            Royal Challengers Bangalore               0.166667
                            Sunrisers Hyderabad                       0.139535
Rajasthan Royals            Chennai Super Kings                       0.146341
                            Delhi Capitals                            0.232558
                            Kings XI Punjab                           0.095238
                            Kolkata Knight Riders                     0.160000
                            Mumbai Indians                            0.181818
                            Royal Challengers Bangalore               0.080000
                            Sunrisers Hyderabad                       0.225806
Royal Challengers Bangalore Chennai Super Kings                       0.090909
                            Delhi Capitals                            0.125000
                            Kings XI Punjab                           0.285714
                            Kolkata Knight Riders                     0.227273
                            Mumbai Indians                            0.055556
                            Rajasthan Royals                          0.156250
                            Sunrisers Hyderabad                       0.170213
Sunrisers Hyderabad         Chennai Super Kings                       0.093023
                            Delhi Capitals                            0.170732
                            Kings XI Punjab                           0.162162
                            Kolkata Knight Riders                     0.228571
                            Mumbai Indians                            0.190476
                            Rajasthan Royals                          0.185185
                            Royal Challengers Bangalore               0.195122

                                                         dismissal_kind_caught  \
batting_team                bowling_team
Chennai Super Kings         Delhi Capitals                            0.757576
                            Kings XI Punjab                           0.578947
                            Kolkata Knight Riders                     0.629630
                            Mumbai Indians                            0.649123
                            Rajasthan Royals                          0.677419
                            Royal Challengers Bangalore               0.533333
                            Sunrisers Hyderabad                       0.457143
Delhi Capitals              Chennai Super Kings                       0.604651
                            Kings XI Punjab                           0.511628
                            Kolkata Knight Riders                     0.666667
                            Mumbai Indians                            0.620000
                            Rajasthan Royals                          0.735294
                            Royal Challengers Bangalore               0.750000
                            Sunrisers Hyderabad                       0.641509
Kings XI Punjab             Chennai Super Kings                       0.777778
                            Delhi Capitals                            0.658537
                            Kolkata Knight Riders                     0.692308
                            Mumbai Indians                            0.709677
                            Rajasthan Royals                          0.777778
                            Royal Challengers Bangalore               0.555556
                            Sunrisers Hyderabad                       0.595238
Kolkata Knight Riders       Chennai Super Kings                       0.738095
                            Delhi Capitals                            0.659574
                            Kings XI Punjab                           0.685714
                            Mumbai Indians                            0.794872
                            Rajasthan Royals                          0.685714
                            Royal Challengers Bangalore               0.657895
                            Sunrisers Hyderabad                       0.714286
Mumbai Indians              Chennai Super Kings                       0.750000
                            Delhi Capitals                            0.680851
                            Kings XI Punjab                           0.694444
                            Kolkata Knight Riders                     0.800000
                            Rajasthan Royals                          0.687500
                            Royal Challengers Bangalore               0.694444
                            Sunrisers Hyderabad                       0.674419
Rajasthan Royals            Chennai Super Kings                       0.682927
                            Delhi Capitals                            0.581395
                            Kings XI Punjab                           0.738095
                            Kolkata Knight Riders                     0.620000
                            Mumbai Indians                            0.696970
                            Royal Challengers Bangalore               0.720000
                            Sunrisers Hyderabad                       0.612903
Royal Challengers Bangalore Chennai Super Kings                       0.681818
                            Delhi Capitals                            0.750000
                            Kings XI Punjab                           0.607143
                            Kolkata Knight Riders                     0.636364
                            Mumbai Indians                            0.750000
                            Rajasthan Royals                          0.656250
                            Sunrisers Hyderabad                       0.617021
Sunrisers Hyderabad         Chennai Super Kings                       0.604651
                            Delhi Capitals                            0.731707
                            Kings XI Punjab                           0.702703
                            Kolkata Knight Riders                     0.485714
                            Mumbai Indians                            0.642857
                            Rajasthan Royals                          0.703704
                            Royal Challengers Bangalore               0.609756

                                                         dismissal_kind_caught and bowled  \
batting_team                bowling_team
Chennai Super Kings         Delhi Capitals                                       0.030303
                            Kings XI Punjab                                      0.000000
                            Kolkata Knight Riders                                0.000000
                            Mumbai Indians                                       0.052632
                            Rajasthan Royals                                     0.000000
                            Royal Challengers Bangalore                          0.000000
                            Sunrisers Hyderabad                                  0.057143
Delhi Capitals              Chennai Super Kings                                  0.023256
                            Kings XI Punjab                                      0.000000
                            Kolkata Knight Riders                                0.027778
                            Mumbai Indians                                       0.000000
                            Rajasthan Royals                                     0.058824
                            Royal Challengers Bangalore                          0.000000
                            Sunrisers Hyderabad                                  0.000000
Kings XI Punjab             Chennai Super Kings                                  0.000000
                            Delhi Capitals                                       0.024390
                            Kolkata Knight Riders                                0.000000
                            Mumbai Indians                                       0.032258
                            Rajasthan Royals                                     0.000000
                            Royal Challengers Bangalore                          0.000000
                            Sunrisers Hyderabad                                  0.023810
Kolkata Knight Riders       Chennai Super Kings                                  0.000000
                            Delhi Capitals                                       0.042553
                            Kings XI Punjab                                      0.028571
                            Mumbai Indians                                       0.000000
                            Rajasthan Royals                                     0.085714
                            Royal Challengers Bangalore                          0.000000
                            Sunrisers Hyderabad                                  0.023810
Mumbai Indians              Chennai Super Kings                                  0.055556
                            Delhi Capitals                                       0.021277
                            Kings XI Punjab                                      0.000000
                            Kolkata Knight Riders                                0.040000
                            Rajasthan Royals                                     0.031250
                            Royal Challengers Bangalore                          0.000000
                            Sunrisers Hyderabad                                  0.023256
Rajasthan Royals            Chennai Super Kings                                  0.073171
                            Delhi Capitals                                       0.023256
                            Kings XI Punjab                                      0.023810
                            Kolkata Knight Riders                                0.080000
                            Mumbai Indians                                       0.030303
                            Royal Challengers Bangalore                          0.040000
                            Sunrisers Hyderabad                                  0.000000
Royal Challengers Bangalore Chennai Super Kings                                  0.068182
                            Delhi Capitals                                       0.000000
                            Kings XI Punjab                                      0.000000
                            Kolkata Knight Riders                                0.045455
                            Mumbai Indians                                       0.000000
                            Rajasthan Royals                                     0.062500
                            Sunrisers Hyderabad                                  0.021277
Sunrisers Hyderabad         Chennai Super Kings                                  0.139535
                            Delhi Capitals                                       0.024390
                            Kings XI Punjab                                      0.027027
                            Kolkata Knight Riders                                0.057143
                            Mumbai Indians                                       0.047619
                            Rajasthan Royals                                     0.037037
                            Royal Challengers Bangalore                          0.024390

                                                         dismissal_kind_lbw  \
batting_team                bowling_team
Chennai Super Kings         Delhi Capitals                         0.030303
                            Kings XI Punjab                        0.105263
                            Kolkata Knight Riders                  0.148148
                            Mumbai Indians                         0.140351
                            Rajasthan Royals                       0.000000
                            Royal Challengers Bangalore            0.000000
                            Sunrisers Hyderabad                    0.057143
Delhi Capitals              Chennai Super Kings                    0.093023
                            Kings XI Punjab                        0.069767
                            Kolkata Knight Riders                  0.055556
                            Mumbai Indians                         0.080000
                            Rajasthan Royals                       0.029412
                            Royal Challengers Bangalore            0.071429
                            Sunrisers Hyderabad                    0.113208
Kings XI Punjab             Chennai Super Kings                    0.055556
                            Delhi Capitals                         0.048780
                            Kolkata Knight Riders                  0.076923
                            Mumbai Indians                         0.032258
                            Rajasthan Royals                       0.000000
                            Royal Challengers Bangalore            0.083333
                            Sunrisers Hyderabad                    0.119048
Kolkata Knight Riders       Chennai Super Kings                    0.047619
                            Delhi Capitals                         0.042553
                            Kings XI Punjab                        0.028571
                            Mumbai Indians                         0.076923
                            Rajasthan Royals                       0.028571
                            Royal Challengers Bangalore            0.052632
                            Sunrisers Hyderabad                    0.071429
Mumbai Indians              Chennai Super Kings                    0.083333
                            Delhi Capitals                         0.063830
                            Kings XI Punjab                        0.083333
                            Kolkata Knight Riders                  0.040000
                            Rajasthan Royals                       0.031250
                            Royal Challengers Bangalore            0.055556
                            Sunrisers Hyderabad                    0.116279
Rajasthan Royals            Chennai Super Kings                    0.048780
                            Delhi Capitals                         0.000000
                            Kings XI Punjab                        0.000000
                            Kolkata Knight Riders                  0.060000
                            Mumbai Indians                         0.060606
                            Royal Challengers Bangalore            0.120000
                            Sunrisers Hyderabad                    0.032258
Royal Challengers Bangalore Chennai Super Kings                    0.000000
                            Delhi Capitals                         0.050000
                            Kings XI Punjab                        0.071429
                            Kolkata Knight Riders                  0.045455
                            Mumbai Indians                         0.027778
                            Rajasthan Royals                       0.031250
                            Sunrisers Hyderabad                    0.042553
Sunrisers Hyderabad         Chennai Super Kings                    0.000000
                            Delhi Capitals                         0.048780
                            Kings XI Punjab                        0.027027
                            Kolkata Knight Riders                  0.085714
                            Mumbai Indians                         0.071429
                            Rajasthan Royals                       0.037037
                            Royal Challengers Bangalore            0.024390

                                                         dismissal_kind_run out  \
batting_team                bowling_team
Chennai Super Kings         Delhi Capitals                             0.060606
                            Kings XI Punjab                            0.052632
                            Kolkata Knight Riders                      0.000000
                            Mumbai Indians                             0.035088
                            Rajasthan Royals                           0.096774
                            Royal Challengers Bangalore                0.133333
                            Sunrisers Hyderabad                        0.142857
Delhi Capitals              Chennai Super Kings                        0.046512
                            Kings XI Punjab                            0.162791
                            Kolkata Knight Riders                      0.055556
                            Mumbai Indians                             0.100000
                            Rajasthan Royals                           0.088235
                            Royal Challengers Bangalore                0.000000
                            Sunrisers Hyderabad                        0.075472
Kings XI Punjab             Chennai Super Kings                        0.000000

In [30]:
matches

,city,date,player_of_match,venue,neutral_venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,eliminator,method,umpire1,umpire2,Team1Won,Team2Won,team_team
id,,,,,,,,,,,,,,,,,,,
1136561,Mumbai,2018-04-07,DJ Bravo,Wankhede Stadium,0,Mumbai Indians,Chennai Super Kings,Chennai Super Kings,field,Chennai Super Kings,True,1.0,N,NaN,CB Gaffaney,A Nand Kishore,False,True,Chennai Super Kings_Mumbai Indians
1136562,Chandigarh,2018-04-08,KL Rahul,"Punjab Cricket Association IS Bindra Stadium, ...",0,Kings XI Punjab,Delhi Capitals,Kings XI Punjab,field,Kings XI Punjab,False,6.0,N,NaN,KN Ananthapadmanabhan,RJ Tucker,True,False,Delhi Capitals_Kings XI Punjab
1136563,Kolkata,2018-04-08,SP Narine,Eden Gardens,0,Kolkata Knight Riders,Royal Challengers Bangalore,Kolkata Knight Riders,field,Kolkata Knight Riders,True,4.0,N,NaN,C Shamshuddin,A Deshmukh,True,False,Kolkata Knight Riders_Royal Challengers Bangalore
1136564,Hyderabad,2018-04-09,S Dhawan,"Rajiv Gandhi International Stadium, Uppal",0,Sunrisers Hyderabad,Rajasthan Royals,Sunrisers Hyderabad,field,Sunrisers Hyderabad,False,9.0,N,NaN,VA Kulkarni,NJ Llong,True,False,Rajasthan Royals_Sunrisers Hyderabad
1136565,Chennai,2018-04-10,SW Billings,"MA Chidambaram Stadium, Chepauk",0,Chennai Super Kings,Kolkata Knight Riders,Chennai Super Kings,field,Chennai Super Kings,True,5.0,N,NaN,CB Gaffaney,AK Chaudhary,True,False,Chennai Super Kings_Kolkata Knight Riders
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1216495,Sharjah,2020-11-03,S Nadeem,Sharjah Cricket Stadium,0,Mumbai Indians,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Sunrisers Hyderabad,False,10.0,N,NaN,C Shamshuddin,RK Illingworth,False,True,Mumbai Indians_Sunrisers Hyderabad
1237177,Dubai,2020-11-05,JJ Bumrah,Dubai International Cricket Stadium,0,Mumbai Indians,Delhi Capitals,Delhi Capitals,field,Mumbai Indians,False,57.0,N,NaN,CB Gaffaney,Nitin Menon,True,False,Delhi Capitals_Mumbai Indians
1237178,Abu Dhabi,2020-11-06,KS Williamson,Sheikh Zayed Stadium,0,Royal Challengers Bangalore,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Sunrisers Hyderabad,False,6.0,N,NaN,PR Reiffel,S Ravi,False,True,Royal Challengers Bangalore_Sunrisers Hyderabad
1237180,Abu Dhabi,2020-11-08,MP Stoinis,Sheikh Zayed Stadium,0,Delhi Capitals,Sunrisers Hyderabad,Delhi Capitals,bat,Delhi Capitals,True,17.0,N,NaN,PR Reiffel,S Ravi,True,False,Delhi Capitals_Sunrisers Hyderabad
1237181,Dubai,2020-11-10,TA Boult,Dubai International Cricket Stadium,0,Delhi Capitals,Mumbai Indians,Delhi Capitals,bat,Mumbai Indians,False,5.0,N,NaN,CB Gaffaney,Nitin Menon,False,True,Delhi Capitals_Mumbai Indians

In [31]:
train_df = pd.DataFrame(columns = ['1WinPer', '2WinPer', '1H2H', 'BAT1_death' ,'BAT1_pp', 'BAT1_mid', 
                                'BOWL1_death' ,'BOWL1_pp', 'BOWL1_mid', 'BAT2_death' ,'BAT2_pp', 'BAT2_mid', 
                                'BOWL2_death' ,'BOWL2_pp', 'BOWL2_mid', 'h2hsco', 'h2hcon', 'h2hwtak', 'h2hwloss',
                               'h2hbhit', 'h2hbconced', '1caught', '1bowled', '1lbw', '1ro', 
                                '2caught', '2bowled', '2lbw', '2ro', 'team1Win'])
test_df = pd.DataFrame(columns = ['1WinPer', '2WinPer', '1H2H', 'BAT1_death' ,'BAT1_pp', 'BAT1_mid', 
                                'BOWL1_death' ,'BOWL1_pp', 'BOWL1_mid', 'BAT2_death' ,'BAT2_pp', 'BAT2_mid', 
                                'BOWL2_death' ,'BOWL2_pp', 'BOWL2_mid', 'h2hsco', 'h2hcon', 'h2hwtak', 'h2hwloss',
                               'h2hbhit', 'h2hbconced', '1caught', '1bowled', '1lbw', '1ro', 
                                '2caught', '2bowled', '2lbw', '2ro', 'team1Win'])

In [32]:
# train_df
for i in range(len(matches)):
    teams = matches['team_team'].iloc[i].split('_')
    team1 = teams[0]
    team2 = teams[1]
    results = []
    results.append(overall_record['Percentage'].loc[team1])
    results.append(overall_record['Percentage'].loc[team2])
    results.append(h2h[matches['team_team'].iloc[i]])
    results.append(run_rate_batting.loc[team1, 'Death'])
    results.append(run_rate_batting.loc[team1, 'Powerplay'])
    results.append(run_rate_batting.loc[team1, 'Middle'])
    results.append(run_rate_bowling.loc[team1, 'Death'])
    results.append(run_rate_bowling.loc[team1, 'Powerplay'])
    results.append(run_rate_bowling.loc[team1, 'Middle'])
    
    results.append(run_rate_batting.loc[team2, 'Death'])
    results.append(run_rate_batting.loc[team2, 'Powerplay'])
    results.append(run_rate_batting.loc[team2, 'Middle'])
    results.append(run_rate_bowling.loc[team2, 'Death'])
    results.append(run_rate_bowling.loc[team2, 'Powerplay'])
    results.append(run_rate_bowling.loc[team2, 'Middle'])
    
    results.append(float(runs.loc[team1, team2]))
    results.append(float(runs.loc[team2, team1]))
    
    results.append(float(wickets.loc[team2, team1])) # wickets taken by team 1
    results.append(float(wickets.loc[team1, team2]))
    
    results.append(float(boundaries.loc[team1, team2])) 
    results.append(float(boundaries.loc[team2, team1]))
    
    
    results += list(dismissal.loc[team2, team1][[1,0,3,4]])
    results += list(dismissal.loc[team1, team2][[1,0,3,4]])
    
    results.append(matches.result.iloc[i])
    
    train_df = train_df.append(pd.Series(results, index = train_df.columns, name = matches.index[i]), ignore_index = False)

In [33]:
# test_df
for i in range(len(test)):
    teams = test['team_team'].iloc[i].split('_')
    team1 = teams[0]
    team2 = teams[1]
    results = []
    results.append(overall_record['Percentage'].loc[team1])
    results.append(overall_record['Percentage'].loc[team2])
    results.append(h2h[matches['team_team'].iloc[i]])
    results.append(run_rate_batting.loc[team1, 'Death'])
    results.append(run_rate_batting.loc[team1, 'Powerplay'])
    results.append(run_rate_batting.loc[team1, 'Middle'])
    results.append(run_rate_bowling.loc[team1, 'Death'])
    results.append(run_rate_bowling.loc[team1, 'Powerplay'])
    results.append(run_rate_bowling.loc[team1, 'Middle'])
    
    results.append(run_rate_batting.loc[team2, 'Death'])
    results.append(run_rate_batting.loc[team2, 'Powerplay'])
    results.append(run_rate_batting.loc[team2, 'Middle'])
    results.append(run_rate_bowling.loc[team2, 'Death'])
    results.append(run_rate_bowling.loc[team2, 'Powerplay'])
    results.append(run_rate_bowling.loc[team2, 'Middle'])
    
    results.append(float(runs.loc[team1, team2]))
    results.append(float(runs.loc[team2, team1]))
    
    results.append(float(wickets.loc[team2, team1])) # wickets taken by team 1
    results.append(float(wickets.loc[team1, team2]))
    
    results.append(float(boundaries.loc[team1, team2])) 
    results.append(float(boundaries.loc[team2, team1]))
    
    
    results += list(dismissal.loc[team2, team1][[1,0,3,4]])
    results += list(dismissal.loc[team1, team2][[1,0,3,4]])
    
    results.append(test.result.iloc[i])
    
    test_df = test_df.append(pd.Series(results, index = test_df.columns, name = test.index[i]), ignore_index = False)

NameError: name 'test' is not defined

In [ ]:
train_X = train_df.drop('team1Win', axis = 1)
test_X = test_df.drop('team1Win', axis = 1)

train_y = train_df['team1Win'].astype('int')
test_y = test_df['team1Win'].astype('int')

In [ ]:
import evalml
import woodwork as ww
from evalml.problem_types import ProblemTypes
from evalml.objectives import LogLossBinary

problem_type = 'binary_classification'
objective =  'Log Loss Binary'



automl = evalml.automl.AutoMLSearch(train_X, train_y, problem_type=ProblemTypes.BINARY, objective = 'accuracy binary')
automl.search()

best_pipeline = automl.best_pipeline

In [ ]:
best_pipeline.predict(test_X).to_series()

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix
rf = RandomForestClassifier(random_state = 1)
rf.fit(train_X, train_y)
predictions = rf.predict(test_X)
print("Accuracy Score: {}".format(accuracy_score(test_y, predictions)))
print("Precision Score: {}".format(precision_score(test_y, predictions)))
print("Recall Score: {}".format(recall_score(test_y, predictions)))
confusion_matrix(test_y, predictions)

In [ ]:
# Feature Importance
import matplotlib.pyplot as plt
import seaborn as sns
plt.figure(figsize = (16,8))
sns.barplot(train_X.columns, rf.feature_importances_)

In [ ]:
pd.set_option('display.max_columns', None)
train_df

In [44]:
to_scale = train_df.columns[3:-11]
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

train_df[to_scale] = scaler.fit_transform(train_df[to_scale])
test_df[to_scale] = scaler.transform(test_df[to_scale])

In [46]:
from xgboost import XGBClassifier

xgb = XGBClassifier()

train_X = train_df.drop('team1Win', axis = 1)
test_X = test_df.drop('team1Win', axis = 1)

train_y = train_df['team1Win'].astype('int')
test_y = test_df['team1Win'].astype('int')

In [204]:
from sklearn.metrics import accuracy_score
xgb.fit(train_X, train_y)
preds = xgb.predict(test_X)
accuracy_score(preds, test_y)

0.4888888888888889

In [203]:
from sklearn.svm import LinearSVC
svc = LinearSVC()
svc.fit(train_X, train_y)
preds = svc.predict(test_X)
accuracy_score(preds, test_y)

0.4888888888888889

In [202]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(13)
knn.fit(train_X, train_y)
preds = knn.predict(test_X)
accuracy_score(preds, test_y)

0.6

In [201]:
from sklearn.svm import SVC
sv = SVC()
sv.fit(train_X, train_y)
preds = sv.predict(test_X)
accuracy_score(preds, test_y)

0.4888888888888889

In [197]:
import tensorflow as tf
nn = tf.keras.models.Sequential()
nn.add(tf.keras.Input(shape=(len(train_X.columns),)))
nn.add(tf.keras.layers.Dense(32, activation = 'relu'))
nn.add(tf.keras.layers.Dense(64, activation = 'relu'))
nn.add(tf.keras.layers.Dense(128, activation = 'relu'))
nn.add(tf.keras.layers.Dense(256, activation = 'relu'))
nn.add(tf.keras.layers.Dense(1, activation = 'sigmoid'))
nn.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_5 (Dense)              (None, 32)                1216
_________________________________________________________________
dense_6 (Dense)              (None, 64)                2112
_________________________________________________________________
dense_7 (Dense)              (None, 128)               8320
_________________________________________________________________
dense_8 (Dense)              (None, 256)               33024
_________________________________________________________________
dense_9 (Dense)              (None, 1)                 257
=================================================================
Total params: 44,929
Trainable params: 44,929
Non-trainable params: 0
_________________________________________________________________

In [198]:
nn.compile(optimizer=tf.keras.optimizers.Adam(lr = 0.01),
              loss = tf.keras.losses.BinaryCrossentropy(),
              metrics = ['accuracy'])

In [199]:
nn.fit(train_X.values, train_y.values, validation_data = (test_X.values, test_y.values) , epochs  = 100, batch_size = 1)

Epoch 1/100
135/135 [==============================] - 1s 5ms/step - loss: 0.7199 - accuracy: 0.4000 - val_loss: 0.6957 - val_accuracy: 0.4667
Epoch 2/100
135/135 [==============================] - 0s 2ms/step - loss: 0.6952 - accuracy: 0.4963 - val_loss: 0.6939 - val_accuracy: 0.4667
Epoch 3/100
135/135 [==============================] - 0s 2ms/step - loss: 0.6944 - accuracy: 0.5111 - val_loss: 0.6962 - val_accuracy: 0.4667
Epoch 4/100
135/135 [==============================] - 0s 2ms/step - loss: 0.6966 - accuracy: 0.4741 - val_loss: 0.6939 - val_accuracy: 0.4667
Epoch 5/100
135/135 [==============================] - 0s 2ms/step - loss: 0.6956 - accuracy: 0.5111 - val_loss: 0.6965 - val_accuracy: 0.4667
Epoch 6/100
135/135 [==============================] - 0s 2ms/step - loss: 0.6951 - accuracy: 0.4593 - val_loss: 0.6964 - val_accuracy: 0.4667
Epoch 7/100
135/135 [==============================] - 0s 2ms/step - loss: 0.6947 - accuracy: 0.5111 - val_loss: 0.6954 - val_accuracy: 0.4667
Epoch 8/100
135/135 [==============================] - 0s 2ms/step - loss: 0.6950 - accuracy: 0.5111 - val_loss: 0.6952 - val_accuracy: 0.4667
Epoch 9/100
135/135 [==============================] - 0s 2ms/step - loss: 0.6942 - accuracy: 0.5111 - val_loss: 0.6947 - val_accuracy: 0.4667
Epoch 10/100
135/135 [==============================] - 0s 3ms/step - loss: 0.6966 - accuracy: 0.4444 - val_loss: 0.6955 - val_accuracy: 0.4667
Epoch 11/100
135/135 [==============================] - 0s 3ms/step - loss: 0.6948 - accuracy: 0.5111 - val_loss: 0.6936 - val_accuracy: 0.4667
Epoch 12/100
135/135 [==============================] - 0s 2ms/step - loss: 0.6946 - accuracy: 0.4519 - val_loss: 0.6937 - val_accuracy: 0.4667
Epoch 13/100
135/135 [==============================] - 0s 4ms/step - loss: 0.6945 - accuracy: 0.4741 - val_loss: 0.6955 - val_accuracy: 0.4667
Epoch 14/100
135/135 [==============================] - 0s 2ms/step - loss: 0.6947 - accuracy: 0.5111 - val_loss: 0.6945 - val_accuracy: 0.4667
Epoch 15/100
135/135 [==============================] - 0s 2ms/step - loss: 0.6951 - accuracy: 0.5111 - val_loss: 0.6951 - val_accuracy: 0.4667
Epoch 16/100
135/135 [==============================] - 0s 2ms/step - loss: 0.6944 - accuracy: 0.4667 - val_loss: 0.6948 - val_accuracy: 0.4667
Epoch 17/100
135/135 [==============================] - 0s 3ms/step - loss: 0.6946 - accuracy: 0.5111 - val_loss: 0.6945 - val_accuracy: 0.4667
Epoch 18/100
135/135 [==============================] - 0s 3ms/step - loss: 0.6957 - accuracy: 0.4296 - val_loss: 0.6950 - val_accuracy: 0.4667
Epoch 19/100
135/135 [==============================] - 1s 4ms/step - loss: 0.6952 - accuracy: 0.4815 - val_loss: 0.6933 - val_accuracy: 0.4667
Epoch 20/100
135/135 [==============================] - 0s 2ms/step - loss: 0.6947 - accuracy: 0.5111 - val_loss: 0.6945 - val_accuracy: 0.4667
Epoch 21/100
135/135 [==============================] - 0s 3ms/step - loss: 0.6944 - accuracy: 0.4889 - val_loss: 0.6938 - val_accuracy: 0.4667
Epoch 22/100
135/135 [==============================] - 0s 2ms/step - loss: 0.6942 - accuracy: 0.5111 - val_loss: 0.6962 - val_accuracy: 0.4667
Epoch 23/100
135/135 [==============================] - 0s 2ms/step - loss: 0.6953 - accuracy: 0.4667 - val_loss: 0.6948 - val_accuracy: 0.4667
Epoch 24/100
135/135 [==============================] - 0s 3ms/step - loss: 0.6952 - accuracy: 0.5111 - val_loss: 0.6937 - val_accuracy: 0.4667
Epoch 25/100
135/135 [==============================] - 0s 2ms/step - loss: 0.6960 - accuracy: 0.4444 - val_loss: 0.6940 - val_accuracy: 0.4667
Epoch 26/100
135/135 [==============================] - 0s 2ms/step - loss: 0.6950 - accuracy: 0.5111 - val_loss: 0.6943 - val_accuracy: 0.4667
Epoch 27/100
135/135 [==============================] - 0s 2ms/step - loss: 0.6949 - accuracy: 0.5111 - val_loss: 0.6960 - val_accuracy: 0.4667
Epoch 28/100
135/135 [==============================] - 1s 4ms/step - loss: 0.6947 - accuracy: 0.5111 - val_loss: 0.6939 - val_accuracy: 0.4667
Epoch 29/100
135/135 [==============================] - 0s 3ms/step - loss: 0.6948 - accuracy: 0.4593 - val_loss: 0.6942 - val_accuracy: 0.4667
Epoch 30/100
135/135 [==============================] - 0s 2ms/step - loss: 0.6952 - accuracy: 0.4815 - val_loss: 0.6947 - val_accuracy: 0.4667
Epoch 31/100
135/135 [==============================] - 0s 2ms/step - loss: 0.6954 - accuracy: 0.4889 - val_loss: 0.6945 - val_accuracy: 0.4667
Epoch 32/100
135/135 [==============================] - 0s 2ms/step - loss: 0.6956 - accuracy: 0.5111 - val_loss: 0.6944 - val_accuracy: 0.4667
Epoch 33/100
135/135 [==============================] - 0s 2ms/step - loss: 0.6952 - accuracy: 0.4963 - val_loss: 0.6944 - val_accuracy: 0.4667
Epoch 34/100
135/135 [==============================] - 0s 2ms/step - loss: 0.6942 - accuracy: 0.4667 - val_loss: 0.6950 - val_accuracy: 0.4667
Epoch 35/100
135/135 [==============================] - 0s 2ms/step - loss: 0.6948 - accuracy: 0.5111 - val_loss: 0.6945 - val_accuracy: 0.4667
Epoch 36/100
135/135 [==============================] - 0s 2ms/step - loss: 0.6948 - accuracy: 0.4815 - val_loss: 0.6944 - val_accuracy: 0.4667
Epoch 37/100
135/135 [==============================] - 0s 2ms/step - loss: 0.6951 - accuracy: 0.5111 - val_loss: 0.6950 - val_accuracy: 0.4667
Epoch 38/100
135/135 [==============================] - 0s 2ms/step - loss: 0.6955 - accuracy: 0.5111 - val_loss: 0.6942 - val_accuracy: 0.4667
Epoch 39/100
135/135 [==============================] - 0s 2ms/step - loss: 0.6958 - accuracy: 0.4815 - val_loss: 0.6967 - val_accuracy: 0.4667
Epoch 40/100
135/135 [==============================] - 1s 4ms/step - loss: 0.6955 - accuracy: 0.5111 - val_loss: 0.6950 - val_accuracy: 0.4667
Epoch 41/100
135/135 [==============================] - 1s 5ms/step - loss: 0.6943 - accuracy: 0.5111 - val_loss: 0.6947 - val_accuracy: 0.4667
Epoch 42/100
135/135 [==============================] - 0s 3ms/step - loss: 0.6944 - accuracy: 0.5111 - val_loss: 0.6948 - val_accuracy: 0.4667
Epoch 43/100
135/135 [==============================] - 0s 2ms/step - loss: 0.6955 - accuracy: 0.4519 - val_loss: 0.6947 - val_accuracy: 0.4667
Epoch 44/100
135/135 [==============================] - 0s 2ms/step - loss: 0.6950 - accuracy: 0.5111 - val_loss: 0.6948 - val_accuracy: 0.4667
Epoch 45/100
135/135 [==============================] - 0s 2ms/step - loss: 0.6943 - accuracy: 0.5111 - val_loss: 0.6938 - val_accuracy: 0.4667
Epoch 46/100
135/135 [==============================] - 0s 2ms/step - loss: 0.6954 - accuracy: 0.5111 - val_loss: 0.6952 - val_accuracy: 0.4667
Epoch 47/100
135/135 [==============================] - 0s 3ms/step - loss: 0.6947 - accuracy: 0.4741 - val_loss: 0.6942 - val_accuracy: 0.4667
Epoch 48/100
135/135 [==============================] - 0s 3ms/step - loss: 0.6956 - accuracy: 0.5111 - val_loss: 0.6946 - val_accuracy: 0.4667
Epoch 49/100
135/135 [==============================] - 0s 3ms/step - loss: 0.6948 - accuracy: 0.4963 - val_loss: 0.6932 - val_accuracy: 0.4667
Epoch 50/100
135/135 [==============================] - 1s 4ms/step - loss: 0.6948 - accuracy: 0.5111 - val_loss: 0.6943 - val_accuracy: 0.4667
Epoch 51/100
135/135 [==============================] - 0s 3ms/step - loss: 0.6956 - accuracy: 0.4741 - val_loss: 0.6932 - val_accuracy: 0.4667
Epoch 52/100
135/135 [==============================] - 0s 4ms/step - loss: 0.6954 - accuracy: 0.4593 - val_loss: 0.6930 - val_accuracy: 0.5333
Epoch 53/100
135/135 [==============================] - 0s 3ms/step - loss: 0.6945 - accuracy: 0.5111 - val_loss: 0.6945 - val_accuracy: 0.4667
Epoch 54/100
135/135 [==============================] - 0s 2ms/step - loss: 0.6953 - accuracy: 0.5111 - val_loss: 0.6943 - val_accuracy: 0.4667
Epoch 55/100
135/135 [==============================] - 0s 2ms/step - loss: 0.6945 - accuracy: 0.5111 - val_loss: 0.6934 - val_accuracy: 0.4667
Epoch 56/100
135/135 [==============================] - 0s 4ms/step - loss: 0.6958 - accuracy: 0.4074 - val_loss: 0.6936 - val_accuracy: 0.4667
Epoch 57/100
135/135 [==============================] - 1s 4ms/step - loss: 0.6953 - accuracy: 0.5111 - val_loss: 0.6951 - val_accuracy: 0.4667
Epoch 58/100
135/135 [==============================] - 1s 4ms/step - loss: 0.6955 - accuracy: 0.4741 - val_loss: 0.6949 - val_accuracy: 0.4667
Epoch 59/100
135/135 [==============================] - 1s 4ms/step - loss: 0.6945 - accuracy: 0.4741 - val_loss: 0.6953 - val_accuracy: 0.4667
Epoch 60/100
135/135 [==============================] - 1s 5ms/step - loss: 0.6944 - accuracy: 0.5111 - val_loss: 0.6947 - val_accuracy: 0.4667
Epoch 61/100
135/135 [==============================] - 0s 2ms/step - loss: 0.6945 - accuracy: 0.5111 - val_loss: 0.6948 - val_accuracy: 0.4667
Epoch 62/100
135/135 [==============================] - 1s 4ms/step - loss: 0.6946 - accuracy: 0.5111 - val_loss: 0.6951 - val_accuracy: 0.4667
Epoch 63/100
135/135 [==============================] - 0s 2ms/step - loss: 0.6950 - accuracy: 0.5111 - val_loss: 0.6946 - val_accuracy: 0.4667
Epoch 64/100
135/135 [==============================] - 0s 2ms/step - loss: 0.6974 - accuracy: 0.5111 - val_loss: 0.6949 - val_accuracy: 0.4667
Epoch 65/100
135/135 [==============================] - 0s 2ms/step - loss: 0.6951 - accuracy: 0.4296 - val_loss: 0.6939 - val_accuracy: 0.4667
Epoch 66/100
135/135 [==============================] - 0s 2ms/step - loss: 0.6954 - accuracy: 0.4519 - val_loss: 0.6937 - val_accuracy: 0.4667
Epoch 67/100
135/135 [==============================] - 0s 2ms/step - loss: 0.6950 - accuracy: 0.5111 - val_loss: 0.6946 - val_accuracy: 0.4667
Epoch 68/100
135/135 [==============================] - 0s 2ms/step - loss: 0.6955 - accuracy: 0.4741 - val_loss: 0.6938 - val_accuracy: 0.4667
Epoch 69/100
135/135 [==============================] - 0s 2ms/step - loss: 0.6946 - accuracy: 0.5111 - val_loss: 0.6952 - val_accuracy: 0.4667
Epoch 70/100
135/135 [==============================] - 0s 2ms/step - loss: 0.6955 - accuracy: 0.4370 - val_loss: 0.6953 - val_accuracy: 0.4667
Epoch 71/100
135/135 [==============================] - 0s 2ms/step - loss: 0.6949 - accuracy: 0.4667 - val_loss: 0.6947 - val_accuracy: 0.4667
Epoch 72/100
135/135 [==============================] - 0s 2ms/step - loss: 0.6948 - accuracy: 0.5111 - val_loss: 0.6943 - val_accuracy: 0.4667
Epoch 73/100
135/135 [==============================] - 0s 2ms/step - loss: 0.6946 - accuracy: 0.4444 - val_loss: 0.6944 - val_accuracy: 0.4667
Epoch 74/100
135/135 [==============================] - 0s 2ms/step - loss: 0.6942 - accuracy: 0.4815 - val_loss: 0.6951 - val_accuracy: 0.4667
Epoch 75/100
135/135 [==============================] - 0s 2ms/step - loss: 0.6943 - accuracy: 0.5111 - val_loss: 0.6957 - val_accuracy: 0.4667
Epoch 76/100
135/135 [==============================] - 0s 2ms/step - loss: 0.6947 - accuracy: 0.5111 - val_loss: 0.6950 - val_accuracy: 0.4667
Epoch 77/100
135/135 [==============================] - 0s 2ms/step - loss: 0.6945 - accuracy: 0.5111 - val_loss: 0.6944 - val_accuracy: 0.4667
Epoch 78/100
135/135 [==============================] - 0s 3ms/step - loss: 0.6959 - accuracy: 0.4667 - val_loss: 0.6961 - val_accuracy: 0.4667
Epoch 79/100
135/135 [==============================] - 0s 3ms/step - loss: 0.6944 - accuracy: 0.5111 - val_loss: 0.6970 - val_accuracy: 0.4667
Epoch 80/100
135/135 [==============================] - 0s 3ms/step - loss: 0.6956 - accuracy: 0.5111 - val_loss: 0.6963 - val_accuracy: 0.4667
Epoch 81/100
135/135 [==============================] - 0s 2ms/step - loss: 0.6948 - accuracy: 0.5111 - val_loss: 0.6947 - val_accuracy: 0.4667
Epoch 82/100
135/135 [==============================] - 0s 2ms/step - loss: 0.6949 - accuracy: 0.5111 - val_loss: 0.6949 - val_accuracy: 0.4667
Epoch 83/100
135/135 [==============================] - 0s 3ms/step - loss: 0.6952 - accuracy: 0.4444 - val_loss: 0.6951 - val_accuracy: 0.4667
Epoch 84/100
135/135 [==============================] - 0s 3ms/step - loss: 0.6946 - accuracy: 0.4519 - val_loss: 0.6945 - val_accuracy: 0.4667
Epoch 85/100
135/135 [==============================] - 0s 3ms/step - loss: 0.6953 - accuracy: 0.5111 - val_loss: 0.6937 - val_accuracy: 0.4667
Epoch 86/100
135/135 [==============================] - 0s 3ms/step - loss: 0.6950 - accuracy: 0.5111 - val_loss: 0.6935 - val_accuracy: 0.4667
Epoch 87/100
135/135 [==============================] - 0s 3ms/step - loss: 0.6949 - accuracy: 0.4667 - val_loss: 0.6939 - val_accuracy: 0.4667
Epoch 88/100
135/135 [==============================] - 0s 3ms/step - loss: 0.6950 - accuracy: 0.4741 - val_loss: 0.6949 - val_accuracy: 0.4667
Epoch 89/100
135/135 [==============================] - 1s 4ms/step - loss: 0.6952 - accuracy: 0.5111 - val_loss: 0.6952 - val_accuracy: 0.4667
Epoch 90/100
135/135 [==============================] - 1s 5ms/step - loss: 0.6953 - accuracy: 0.4444 - val_loss: 0.6945 - val_accuracy: 0.4667
Epoch 91/100
135/135 [==============================] - 0s 3ms/step - loss: 0.6940 - accuracy: 0.5111 - val_loss: 0.6951 - val_accuracy: 0.4667
Epoch 92/100
135/135 [==============================] - 0s 3ms/step - loss: 0.6951 - accuracy: 0.5111 - val_loss: 0.6946 - val_accuracy: 0.4667
Epoch 93/100
135/135 [==============================] - 0s 3ms/step - loss: 0.6954 - accuracy: 0.5111 - val_loss: 0.6953 - val_accuracy: 0.4667
Epoch 94/100
135/135 [==============================] - 0s 3ms/step - loss: 0.6958 - accuracy: 0.4148 - val_loss: 0.6950 - val_accuracy: 0.4667
Epoch 95/100
135/135 [==============================] - 0s 3ms/step - loss: 0.6952 - accuracy: 0.4519 - val_loss: 0.6958 - val_accuracy: 0.4667
Epoch 96/100
135/135 [==============================] - 1s 4ms/step - loss: 0.6949 - accuracy: 0.4963 - val_loss: 0.6964 - val_accuracy: 0.4667
Epoch 97/100
135/135 [==============================] - 1s 4ms/step - loss: 0.6952 - accuracy: 0.5111 - val_loss: 0.6969 - val_accuracy: 0.4667
Epoch 98/100
135/135 [==============================] - 0s 2ms/step - loss: 0.6951 - accuracy: 0.4519 - val_loss: 0.6942 - val_accuracy: 0.4667
Epoch 99/100
135/135 [==============================] - 0s 2ms/step - loss: 0.6943 - accuracy: 0.4741 - val_loss: 0.6952 - val_accuracy: 0.4667
Epoch 100/100
135/135 [==============================] - 1s 4ms/step - loss: 0.6949 - accuracy: 0.4741 - val_loss: 0.6953 - val_accuracy: 0.4667

In [191]:
from sklearn.feature_selection import SelectKBest, chi2
from xgboost import XGBClassifier
xgb = XGBClassifier()
for i in range(1, 20):
    #best = SelectKBest(chi2, k=i)
    xgb.fit(train_X, train_y)
    preds = xgb.predict(test_X)
    print(i, accuracy_score(preds, test_y))

1 0.4888888888888889
2 0.4888888888888889
3 0.4888888888888889
4 0.4888888888888889
5 0.4888888888888889
6 0.4888888888888889
7 0.4888888888888889
8 0.4888888888888889
9 0.4888888888888889
10 0.4888888888888889
11 0.4888888888888889
12 0.4888888888888889
13 0.4888888888888889
14 0.4888888888888889
15 0.4888888888888889
16 0.4888888888888889
17 0.4888888888888889
18 0.4888888888888889
19 0.4888888888888889

In [193]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()
for i in range(1, 20):
    #best = SelectKBest(chi2, k=i)
    rf.fit(train_X, train_y)
    preds = rf.predict(test_X)
    print(i, accuracy_score(preds, test_y))

1 0.4888888888888889
2 0.4444444444444444
3 0.4444444444444444
4 0.4444444444444444
5 0.4666666666666667
6 0.4888888888888889
7 0.4444444444444444
8 0.4222222222222222
9 0.5111111111111111
10 0.4222222222222222
11 0.4888888888888889
12 0.4666666666666667
13 0.4
14 0.4444444444444444
15 0.4444444444444444
16 0.4666666666666667
17 0.4666666666666667
18 0.4666666666666667
19 0.4

In [194]:
for i in range(1, 20):
    best = SelectKBest(chi2, k=i)
    knn.fit(best.fit_transform(train_X, train_y), train_y)
    preds = knn.predict(best.transform(test_X))
    print(i, accuracy_score(preds, test_y))

1 0.5333333333333333
2 0.4
3 0.4666666666666667
4 0.4666666666666667
5 0.4444444444444444
6 0.4444444444444444
7 0.4444444444444444
8 0.5111111111111111
9 0.4888888888888889
10 0.5111111111111111
11 0.4888888888888889
12 0.4666666666666667
13 0.4
14 0.4444444444444444
15 0.4666666666666667
16 0.4666666666666667
17 0.4666666666666667
18 0.4444444444444444
19 0.5333333333333333

In [36]:
squads = pd.read_csv('squad.csv')
squads

                    team             player
0    Chennai Super Kings      Ambati Rayudu
1    Chennai Super Kings    C Hari Nishanth
2    Chennai Super Kings  Cheteshwar Pujara
3    Chennai Super Kings     Faf du Plessis
4    Chennai Super Kings      Robin Uthappa
..                   ...                ...
185  Sunrisers Hyderabad   Mujeeb Ur Rahman
186  Sunrisers Hyderabad        Rashid Khan
187  Sunrisers Hyderabad     Sandeep Sharma
188  Sunrisers Hyderabad     Shahbaz Nadeem
189  Sunrisers Hyderabad      Siddarth Kaul

[190 rows x 2 columns]

In [37]:
delivery[delivery.batsman.str.contains('Curran')].batsman.unique()

array(['TK Curran', 'SM Curran'], dtype=object)

In [38]:
squads['runs_scored'] = 0
squads['balls_faced'] = 0
squads['dismissed'] = 0

squads['runs_conceded'] = 0
squads['balls_bowled'] = 0
squads['wickets_taken'] = 0

In [39]:
squads['added'] = False

In [40]:
def find_player_stats(demo):
    play = demo.split()[-1]
    data = []
    if delivery[delivery.batsman.str.contains(play)].batsman.nunique() > 1:
        players = delivery[delivery.batsman.str.contains(play)].batsman.unique()
        first_letter = demo[0]
        reduced = []
        for plays in players:
            if first_letter == plays[0]:
                reduced.append(plays)
        if len(reduced) == 1:
            play = reduced[0]
        else:
            return False
    
    if delivery[(delivery.batsman.str.contains(play)) | (delivery.bowler.str.contains(play))].index.nunique() < 22:
        return False
    data.append(delivery[delivery.batsman.str.contains(play)].batsman_runs.sum()) # runs scored
    data.append(delivery[delivery.batsman.str.contains(play)].ball.count()) # balls faced
    data.append(delivery[delivery.batsman.str.contains(play)].is_wicket.sum()) # dismissed

    data.append(delivery[delivery.bowler.str.contains(play)].total_runs.sum()) # runs conceded
    data.append(delivery[delivery.bowler.str.contains(play)].ball.count()) # balls bowled
    data.append(delivery[delivery.bowler.str.contains(play)].is_wicket.sum()) # wickets taken

    data.append(True) # added values 
    return data

In [41]:
squads['extracted'] = squads.player.apply(lambda x: find_player_stats(x))

In [42]:
squads[squads.extracted == False]

,team,player,runs_scored,balls_faced,dismissed,runs_conceded,balls_bowled,wickets_taken,added,extracted
1,Chennai Super Kings,C Hari Nishanth,0,0,0,0,0,0,False,False
2,Chennai Super Kings,Cheteshwar Pujara,0,0,0,0,0,0,False,False
5,Chennai Super Kings,Ruturaj Gaikwad,0,0,0,0,0,0,False,False
7,Chennai Super Kings,Bhagath Varma,0,0,0,0,0,0,False,False
10,Chennai Super Kings,Mitchell Santner,0,0,0,0,0,0,False,False
...,...,...,...,...,...,...,...,...,...,...
181,Sunrisers Hyderabad,Basil Thampi,0,0,0,0,0,0,False,False
183,Sunrisers Hyderabad,Jagadeesha Suchith,0,0,0,0,0,0,False,False
184,Sunrisers Hyderabad,Khaleel Ahmed,0,0,0,0,0,0,False,False
185,Sunrisers Hyderabad,Mujeeb Ur Rahman,0,0,0,0,0,0,False,False
188,Sunrisers Hyderabad,Shahbaz Nadeem,0,0,0,0,0,0,False,False

In [45]:
# these are relatively insignificant players so we will just drop them

squads = squads[squads.extracted != False]
pd.set_option('display.max_rows', None)
squads

,team,player,runs_scored,balls_faced,dismissed,runs_conceded,balls_bowled,wickets_taken,added,extracted
0,Chennai Super Kings,Ambati Rayudu,1243,1006,35,0,0,0,True,"[1243, 1006, 35, 0, 0, 0, True]"
3,Chennai Super Kings,Faf du Plessis,1007,785,28,0,0,0,True,"[1007, 785, 28, 0, 0, 0, True]"
4,Chennai Super Kings,Robin Uthappa,829,698,38,0,0,0,True,"[829, 698, 38, 0, 0, 0, True]"
6,Chennai Super Kings,Suresh Raina,828,675,28,6,6,0,True,"[828, 675, 28, 6, 6, 0, True]"
8,Chennai Super Kings,Dwayne Bravo,228,167,11,1054,736,38,True,"[228, 167, 11, 1054, 736, 38, True]"
9,Chennai Super Kings,Krishnappa Gowtham,186,113,13,576,414,14,True,"[186, 113, 13, 576, 414, 14, True]"
12,Chennai Super Kings,Ravindra Jadeja,427,316,12,975,797,33,True,"[427, 316, 12, 975, 797, 33, True]"
13,Chennai Super Kings,Sam Curran,281,200,12,673,472,25,True,"[281, 200, 12, 673, 472, 25, True]"
14,Chennai Super Kings,MS Dhoni,1071,813,21,0,0,0,True,"[1071, 813, 21, 0, 0, 0, True]"
16,Chennai Super Kings,Deepak Chahar,64,52,6,1169,969,44,True,"[64, 52, 6, 1169, 969, 44, True]"
18,Chennai Super Kings,Imran Tahir,15,12,0,711,580,33,True,"[15, 12, 0, 711, 580, 33, True]"
24,Chennai Super Kings,Shardul Thakur,41,33,2,997,688,36,True,"[41, 33, 2, 997, 688, 36, True]"
25,Delhi Capitals,Ajinkya Rahane,876,723,34,0,0,0,True,"[876, 723, 34, 0, 0, 0, True]"
26,Delhi Capitals,Prithvi Shaw,826,605,37,0,0,0,True,"[826, 605, 37, 0, 0, 0, True]"
28,Delhi Capitals,Shikhar Dhawan,1636,1203,44,0,0,0,True,"[1636, 1203, 44, 0, 0, 0, True]"
30,Delhi Capitals,Steven Smith,630,530,22,0,0,0,True,"[630, 530, 22, 0, 0, 0, True]"
32,Delhi Capitals,Axar Patel,307,251,22,918,773,26,True,"[307, 251, 22, 918, 773, 26, True]"
35,Delhi Capitals,Marcus Stoinis,662,487,23,555,353,18,True,"[662, 487, 23, 555, 353, 18, True]"
36,Delhi Capitals,Rishabh Pant,1515,1035,38,0,0,0,True,"[1515, 1035, 38, 0, 0, 0, True]"
39,Delhi Capitals,Amit Mishra,22,28,2,608,530,27,True,"[22, 28, 2, 608, 530, 27, True]"
43,Delhi Capitals,Kagiso Rabada,70,67,6,938,703,58,True,"[70, 67, 6, 938, 703, 58, True]"
48,Delhi Capitals,Umesh Yadav,28,40,6,885,615,30,True,"[28, 40, 6, 885, 615, 30, True]"
52,Kolkata Knight Riders,Nitish Rana,1000,738,38,140,101,7,True,"[1000, 738, 38, 140, 101, 7, True]"
53,Kolkata Knight Riders,Rahul Tripathi,597,481,25,0,0,0,True,"[597, 481, 25, 0, 0, 0, True]"
54,Kolkata Knight Riders,Shubman Gill,939,766,27,0,0,0,True,"[939, 766, 27, 0, 0, 0, True]"
55,Kolkata Knight Riders,Andre Russell,943,532,30,826,535,31,True,"[943, 532, 30, 826, 535, 31, True]"
58,Kolkata Knight Riders,Sunil Narine,621,380,32,1134,874,34,True,"[621, 380, 32, 1134, 874, 34, True]"
59,Kolkata Knight Riders,Venkatesh Iyer,1393,1147,43,0,0,0,True,"[1393, 1147, 43, 0, 0, 0, True]"
60,Kolkata Knight Riders,Dinesh Karthik,920,663,30,0,0,0,True,"[920, 663, 30, 0, 0, 0, True]"
63,Kolkata Knight Riders,Harbhajan Singh,30,41,3,585,462,25,True,"[30, 41, 3, 585, 462, 25, True]"
65,Kolkata Knight Riders,Kuldeep Yadav,37,54,2,804,589,24,True,"[37, 54, 2, 804, 589, 24, True]"
69,Kolkata Knight Riders,Prasidh Krishna,3,11,1,810,540,20,True,"[3, 11, 1, 810, 540, 20, True]"
74,Punjab Kings,Chris Gayle,1146,822,27,5,5,0,True,"[1146, 822, 27, 5, 5, 0, True]"
76,Punjab Kings,Mandeep Singh,547,426,21,26,12,0,True,"[547, 426, 21, 26, 12, 0, True]"
77,Punjab Kings,Mayank Agarwal,876,618,31,0,0,0,True,"[876, 618, 31, 0, 0, 0, True]"
86,Punjab Kings,KL Rahul,1922,1398,36,0,0,0,True,"[1922, 1398, 36, 0, 0, 0, True]"
94,Punjab Kings,Mohammed Shami,10,11,3,1095,749,47,True,"[10, 11, 3, 1095, 749, 47, True]"
100,Mumbai Indians,Chris Lynn,896,678,27,0,0,0,True,"[896, 678, 27, 0, 0, 0, True]"
101,Mumbai Indians,Rohit Sharma,1023,814,42,0,0,0,True,"[1023, 814, 42, 0, 0, 0, True]"
103,Mumbai Indians,Suryakumar Yadav,1416,1058,37,0,0,0,True,"[1416, 1058, 37, 0, 0, 0, True]"
106,Mumbai Indians,Hardik Pandya,943,591,26,788,539,35,True,"[943, 591, 26, 788, 539, 35, True]"
108,Mumbai Indians,Kieron Pollard,680,436,22,190,138,4,True,"[680, 436, 22, 190, 138, 4, True]"
109,Mumbai Indians,Krunal Pandya,520,414,26,1012,843,32,True,"[520, 414, 26, 1012, 843, 32, True]"
112,Mumbai Indians,Ishan Kishan,892,652,26,0,0,0,True,"[892, 652, 26, 0, 0, 0, True]"
113,Mumbai Indians,Quinton de Kock,1233,933,35,0,0,0,True,"[1233, 933, 35, 0, 0, 0, True]"
116,Mumbai Indians,Jasprit Bumrah,15,15,1,1228,1083,66,True,"[15, 15, 1, 1228, 1083, 66, True]"
120,Mumbai Indians,Piyush Chawla,69,74,8,1015,691,31,True,"[69, 74, 8, 1015, 691, 31, True]"
121,Mumbai Indians,Rahul Chahar,14,15,2,749,610,29,True,"[14, 15, 2, 749, 610, 29, True]"
122,Mumbai Indians,Trent Boult,7,7,3,1097,797,51,True,"[7, 7, 3, 1097, 797, 51, True]"
129,Royal Challengers Bangalore,Virat Kohli,1460,1117,37,0,0,0,True,"[1460, 1117, 37, 0, 0, 0, True]"
132,Royal Challengers Bangalore,Glenn Maxwell,277,234,19,303,224,8,True,"[277, 234, 19, 303, 224, 8, True]"
134,Royal Challengers Bangalore,Washington Sundar,177,142,12,569,478,17,True,"[177, 142, 12, 569, 478, 17, True]"
135,Royal Challengers Bangalore,AB de Villiers,1376,866,29,0,0,0,True,"[1376, 866, 29, 0, 0, 0, True]"
141,Royal Challengers Bangalore,Mohammed Siraj,46,52,5,887,615,31,True,"[46, 52, 5, 887, 615, 31, True]"
142,Royal Challengers Bangalore,Navdeep Saini,29,31,2,795,587,19,True,"[29, 31, 2, 795, 587, 19, True]"
144,Royal Challengers Bangalore,Yuzvendra Chahal,7,25,3,1182,969,52,True,"[7, 25, 3, 1182, 969, 52, True]"
149,Rajasthan Royals,Chris Morris,112,85,11,674,497,28,True,"[112, 85, 11, 674, 497, 28, True]"
151,Rajasthan Royals,Rahul Tewatia,331,256,11,543,459,19,True,"[331, 256, 11, 543, 459, 19, True]"
153,Rajasthan Royals,Shreyas Gopal,150,134,10,1018,782,42,True,"[150, 134, 10, 1018, 782, 42, True]"
155,Rajasthan Royals,Jos Buttler,1187,811,29,0,0,0,True,"[1187, 811, 29, 0, 0, 0, True]"
156,Rajasthan Royals,Sanju Samson,1158,805,36,0,0,0,True,"[1158, 805, 36, 0, 0, 0, True]"
160,Rajasthan Royals,Jaydev Unadkat,59,54,7,1119,690,28,True,"[59, 54, 7, 1119, 690, 28, True]"
163,Rajasthan Royals,Kuldip Yadav,37,54,2,804,589,24,True,"[37, 54, 2, 804, 589, 24, True]"
167,Sunrisers Hyderabad,David Warner,1240,918,25,2,2,0,True,"[1240, 918, 25, 2, 2, 0, True]"
169,Sunrisers Hyderabad,Kane Williamson,1208,897,29,24,12,0,True,"[1208, 897, 29, 24, 12, 0, True]"
171,Sunrisers Hyderabad,Manish Pandey,1053,874,32,0,0,0,True,"[1053, 874, 32, 0, 0, 0, True]"
177,Sunrisers Hyderabad,Vijay Shankar,553,451,19,210,170,7,True,"[553, 451, 19, 210, 170, 7, True]"
182,Sunrisers Hyderabad,Bhuvneshwar Kumar,25,39,6,923,741,29,True,"[25, 39, 6, 923, 741, 29, True]"
186,Sunrisers Hyderabad,Rashid Khan,128,90,14,1205,1162,62,True,"[128, 90, 14, 1205, 1162, 62, True]"
187,Sunrisers Hyderabad,Sandeep Sharma,18,23,4,1063,855,41,True,"[18, 23, 4, 1063, 855, 41, True]"
189,Sunrisers Hyderabad,Siddarth Kaul,3,15,3,865,597,32,True,"[3, 15, 3, 865, 597, 32, True]"

In [46]:
for i in range(len(squads.columns[2:-1])):
    col = squads.columns[2:-1][i]
    squads[col] = squads['extracted'].apply(lambda x: x[i])

In [47]:
squads['added'].value_counts()

True    71
Name: added, dtype: int64

In [48]:
squads.drop(columns = ['added', 'extracted'], inplace = True)

In [49]:
squad_sum = squads.groupby('team').sum()
squad_sum

,runs_scored,balls_faced,dismissed,runs_conceded,balls_bowled,wickets_taken
team,,,,,,
Chennai Super Kings,6220,4870,206,6161,4662,223
Delhi Capitals,6572,4969,234,3904,2974,159
Kolkata Knight Riders,6483,4813,231,4299,3101,141
Mumbai Indians,7708,5687,255,6079,4701,248
Punjab Kings,4501,3275,118,1126,766,47
Rajasthan Royals,3034,2199,106,4158,3017,141
Royal Challengers Bangalore,3372,2467,107,3736,2873,127
Sunrisers Hyderabad,4228,3307,132,4292,3539,171

In [50]:
squad_sum['batting_avg'] =squad_sum.runs_scored /  squad_sum.dismissed

In [51]:
squad_sum['batting_sr'] =squad_sum.runs_scored /  squad_sum.balls_faced

In [52]:
squad_sum['bowling_sr'] =squad_sum.balls_bowled /  squad_sum.wickets_taken
squad_sum['bowling_avg'] =squad_sum.runs_conceded /  squad_sum.wickets_taken

In [53]:
ss = list(squad_sum.index)
ss[-4] = 'Kings XI Punjab'
squad_sum.index = ss
squad_sum

,runs_scored,balls_faced,dismissed,runs_conceded,balls_bowled,wickets_taken,batting_avg,batting_sr,bowling_sr,bowling_avg
Chennai Super Kings,6220,4870,206,6161,4662,223,30.194175,1.277207,20.905830,27.627803
Delhi Capitals,6572,4969,234,3904,2974,159,28.085470,1.322600,18.704403,24.553459
Kolkata Knight Riders,6483,4813,231,4299,3101,141,28.064935,1.346977,21.992908,30.489362
Mumbai Indians,7708,5687,255,6079,4701,248,30.227451,1.355372,18.955645,24.512097
Kings XI Punjab,4501,3275,118,1126,766,47,38.144068,1.374351,16.297872,23.957447
Rajasthan Royals,3034,2199,106,4158,3017,141,28.622642,1.379718,21.397163,29.489362
Royal Challengers Bangalore,3372,2467,107,3736,2873,127,31.514019,1.366842,22.622047,29.417323
Sunrisers Hyderabad,4228,3307,132,4292,3539,171,32.030303,1.278500,20.695906,25.099415

In [75]:
train_df = pd.DataFrame(columns = ['1WinPer', '2WinPer', '1H2H', 'BAT1_death' ,'BAT1_pp', 'BAT1_mid', 
                                'BOWL1_death' ,'BOWL1_pp', 'BOWL1_mid', 'BAT2_death' ,'BAT2_pp', 'BAT2_mid', 
                                'BOWL2_death' ,'BOWL2_pp', 'BOWL2_mid', 'h2hsco', 'h2hcon', 'h2hwtak', 'h2hwloss',
                               'h2hbhit', 'h2hbconced', '1caught', '1bowled', '1lbw', '1ro', 
                                '2caught', '2bowled', '2lbw', '2ro', '1bat_avg', '1bat_sr', '1bowl_sr', '1bowl_avg',
                                   '2bat_avg', '2bat_sr', '2bowl_sr', '2bowl_avg','team1Win'])
test_df = pd.DataFrame(columns = ['1WinPer', '2WinPer', '1H2H', 'BAT1_death' ,'BAT1_pp', 'BAT1_mid', 
                                'BOWL1_death' ,'BOWL1_pp', 'BOWL1_mid', 'BAT2_death' ,'BAT2_pp', 'BAT2_mid', 
                                'BOWL2_death' ,'BOWL2_pp', 'BOWL2_mid', 'h2hsco', 'h2hcon', 'h2hwtak', 'h2hwloss',
                               'h2hbhit', 'h2hbconced', '1caught', '1bowled', '1lbw', '1ro', 
                                '2caught', '2bowled', '2lbw', '2ro', '1bat_avg', '1bat_sr', '1bowl_sr', '1bowl_avg',
                                   '2bat_avg', '2bat_sr', '2bowl_sr', '2bowl_avg','team1Win'])

In [76]:
# train_df
for i in range(len(matches)):
    teams = matches['team_team'].iloc[i].split('_')
    team1 = teams[0]
    team2 = teams[1]
    results = []
    results.append(overall_record['Percentage'].loc[team1])
    results.append(overall_record['Percentage'].loc[team2])
    results.append(h2h[matches['team_team'].iloc[i]])
    results.append(run_rate_batting.loc[team1, 'Death'])
    results.append(run_rate_batting.loc[team1, 'Powerplay'])
    results.append(run_rate_batting.loc[team1, 'Middle'])
    results.append(run_rate_bowling.loc[team1, 'Death'])
    results.append(run_rate_bowling.loc[team1, 'Powerplay'])
    results.append(run_rate_bowling.loc[team1, 'Middle'])
    
    results.append(run_rate_batting.loc[team2, 'Death'])
    results.append(run_rate_batting.loc[team2, 'Powerplay'])
    results.append(run_rate_batting.loc[team2, 'Middle'])
    results.append(run_rate_bowling.loc[team2, 'Death'])
    results.append(run_rate_bowling.loc[team2, 'Powerplay'])
    results.append(run_rate_bowling.loc[team2, 'Middle'])
    
    results.append(float(runs.loc[team1, team2]))
    results.append(float(runs.loc[team2, team1]))
    
    results.append(float(wickets.loc[team2, team1])) # wickets taken by team 1
    results.append(float(wickets.loc[team1, team2]))
    
    results.append(float(boundaries.loc[team1, team2])) 
    results.append(float(boundaries.loc[team2, team1]))
    
    
    results += list(dismissal.loc[team2, team1][[1,0,3,4]])
    results += list(dismissal.loc[team1, team2][[1,0,3,4]])
    
    results += list(squad_sum.loc[team1, ['batting_avg', 'batting_sr', 'bowling_sr', 'bowling_avg']])
    results += list(squad_sum.loc[team2, ['batting_avg', 'batting_sr', 'bowling_sr', 'bowling_avg']])
    results.append(matches.result.iloc[i])
    
    train_df = train_df.append(pd.Series(results, index = train_df.columns, name = matches.index[i]), ignore_index = False)

In [78]:
pd.set_option('display.max_columns', None)
train_df.shape

(180, 38)

In [79]:
train_X = train_df.drop('team1Win', axis = 1)
test_X = test_df.drop('team1Win', axis = 1)

train_y = train_df['team1Win'].astype('int')
test_y = test_df['team1Win'].astype('int')

In [80]:
to_scale = list(train_X.columns[3:19])  + list(train_X.columns[-8:])
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

train_X[to_scale] = scaler.fit_transform(train_X[to_scale])

In [59]:
from sklearn.model_selection import GridSearchCV
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()


params = dict(n_neighbors = range(10, 20), weights = ['uniform' , 'distance'], leaf_size = range(20, 50, 5), 
              metric = ['minkowski', 'euclidean', 'manhattan'])

clf = GridSearchCV(knn, params, scoring = 'accuracy', cv = 5, verbose = True)
search = clf.fit(train_X, train_y)
search.best_params_

Fitting 5 folds for each of 360 candidates, totalling 1800 fits

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done 1800 out of 1800 | elapsed:   12.3s finished

{'leaf_size': 20,
 'metric': 'manhattan',
 'n_neighbors': 13,
 'weights': 'uniform'}

In [60]:
fixtures = pd.read_csv('fixtures.csv', index_col = 0)

In [81]:
fix = pd.DataFrame(columns = train_df.columns[:-1])

In [82]:
fix.shape

(0, 37)

In [74]:
train_X.shape

(180, 37)

In [62]:
fixtures

                             V1                           V2  V3
1                Mumbai Indians          Chennai Super Kings NaN
2                Mumbai Indians               Delhi Capitals NaN
3                Mumbai Indians              Kings XI Punjab NaN
4                Mumbai Indians  Royal Challengers Bangalore NaN
5                Mumbai Indians        Kolkata Knight Riders NaN
6                Mumbai Indians             Rajasthan Royals NaN
7                Mumbai Indians          Sunrisers Hyderabad NaN
8           Chennai Super Kings               Delhi Capitals NaN
9           Chennai Super Kings              Kings XI Punjab NaN
10          Chennai Super Kings  Royal Challengers Bangalore NaN
11          Chennai Super Kings        Kolkata Knight Riders NaN
12          Chennai Super Kings             Rajasthan Royals NaN
13          Chennai Super Kings          Sunrisers Hyderabad NaN
14               Delhi Capitals              Kings XI Punjab NaN
15               Delhi Capitals  Royal Challengers Bangalore NaN
16               Delhi Capitals        Kolkata Knight Riders NaN
17               Delhi Capitals             Rajasthan Royals NaN
18               Delhi Capitals          Sunrisers Hyderabad NaN
19              Kings XI Punjab  Royal Challengers Bangalore NaN
20              Kings XI Punjab        Kolkata Knight Riders NaN
21              Kings XI Punjab             Rajasthan Royals NaN
22              Kings XI Punjab          Sunrisers Hyderabad NaN
23  Royal Challengers Bangalore        Kolkata Knight Riders NaN
24  Royal Challengers Bangalore             Rajasthan Royals NaN
25  Royal Challengers Bangalore          Sunrisers Hyderabad NaN
26        Kolkata Knight Riders             Rajasthan Royals NaN
27        Kolkata Knight Riders          Sunrisers Hyderabad NaN
28             Rajasthan Royals          Sunrisers Hyderabad NaN
29               Mumbai Indians          Chennai Super Kings NaN
30               Mumbai Indians               Delhi Capitals NaN
31               Mumbai Indians              Kings XI Punjab NaN
32               Mumbai Indians  Royal Challengers Bangalore NaN
33               Mumbai Indians        Kolkata Knight Riders NaN
34               Mumbai Indians             Rajasthan Royals NaN
35               Mumbai Indians          Sunrisers Hyderabad NaN
36          Chennai Super Kings               Delhi Capitals NaN
37          Chennai Super Kings              Kings XI Punjab NaN
38          Chennai Super Kings  Royal Challengers Bangalore NaN
39          Chennai Super Kings        Kolkata Knight Riders NaN
40          Chennai Super Kings             Rajasthan Royals NaN
41          Chennai Super Kings          Sunrisers Hyderabad NaN
42               Delhi Capitals              Kings XI Punjab NaN
43               Delhi Capitals  Royal Challengers Bangalore NaN
44               Delhi Capitals        Kolkata Knight Riders NaN
45               Delhi Capitals             Rajasthan Royals NaN
46               Delhi Capitals          Sunrisers Hyderabad NaN
47              Kings XI Punjab  Royal Challengers Bangalore NaN
48              Kings XI Punjab        Kolkata Knight Riders NaN
49              Kings XI Punjab             Rajasthan Royals NaN
50              Kings XI Punjab          Sunrisers Hyderabad NaN
51  Royal Challengers Bangalore        Kolkata Knight Riders NaN
52  Royal Challengers Bangalore             Rajasthan Royals NaN
53  Royal Challengers Bangalore          Sunrisers Hyderabad NaN
54        Kolkata Knight Riders             Rajasthan Royals NaN
55        Kolkata Knight Riders          Sunrisers Hyderabad NaN
56             Rajasthan Royals          Sunrisers Hyderabad NaN

In [ ]:
# fix_df
for i in range(len(fixtures)):
    #teams = matches['team_team'].iloc[i].split('_')
    team1, team2 = tuple(sorted([fixtures.iloc[i,0], fixtures.iloc[i,1]]))
    print(team1, team2)
    results = []
    results.append(overall_record['Percentage'].loc[team1])
    results.append(overall_record['Percentage'].loc[team2])
    print(len(results))
    results.append(h2h.loc[team1 + '_' + team2])
    print(len(results))
    results.append(run_rate_batting.loc[team1, 'Death'])
    print(len(results))
    results.append(run_rate_batting.loc[team1, 'Powerplay'])
    results.append(run_rate_batting.loc[team1, 'Middle'])
    results.append(run_rate_bowling.loc[team1, 'Death'])
    results.append(run_rate_bowling.loc[team1, 'Powerplay'])
    results.append(run_rate_bowling.loc[team1, 'Middle'])
    
    results.append(run_rate_batting.loc[team2, 'Death'])
    results.append(run_rate_batting.loc[team2, 'Powerplay'])
    results.append(run_rate_batting.loc[team2, 'Middle'])
    results.append(run_rate_bowling.loc[team2, 'Death'])
    results.append(run_rate_bowling.loc[team2, 'Powerplay'])
    results.append(run_rate_bowling.loc[team2, 'Middle'])
    print(len(results))
    
    results.append(float(runs.loc[team1, team2]))
    results.append(float(runs.loc[team2, team1]))
    print(len(results))
    
    results.append(float(wickets.loc[team2, team1])) # wickets taken by team 1
    results.append(float(wickets.loc[team1, team2]))
    print(len(results))
    
    results.append(float(boundaries.loc[team1, team2])) 
    results.append(float(boundaries.loc[team2, team1]))
    print(len(results))
    
    results += list(dismissal.loc[team2, team1][[1,0,3,4]])
    results += list(dismissal.loc[team1, team2][[1,0,3,4]])
    print(len(results))
    
    results += list(squad_sum.loc[team1, ['batting_avg', 'batting_sr', 'bowling_sr', 'bowling_avg']])
    results += list(squad_sum.loc[team2, ['batting_avg', 'batting_sr', 'bowling_sr', 'bowling_avg']])
    print(len(results))
    
    fix = fix.append(pd.Series(results, index = train_df.columns[:-1], name = fixtures.index[i]), ignore_index = False)

In [85]:
fix.shape

(56, 37)

In [124]:
 fixtures.iloc[2,1]

'Kings XI Punjab'

In [65]:
for i in range(len(fixtures)):
    #teams = matches['team_team'].iloc[i].split('_')
    team1, team2 = tuple(sorted([fixtures.iloc[i,0], fixtures.iloc[i,1]]))
    print(team1, team2)
    fixtures['V1'].iloc[i]= team1
    fixtures['V2'].iloc[i]= team2
fixtures

Chennai Super Kings Mumbai Indians
Delhi Capitals Mumbai Indians
Kings XI Punjab Mumbai Indians
Mumbai Indians Royal Challengers Bangalore
Kolkata Knight Riders Mumbai Indians
Mumbai Indians Rajasthan Royals
Mumbai Indians Sunrisers Hyderabad
Chennai Super Kings Delhi Capitals
Chennai Super Kings Kings XI Punjab
Chennai Super Kings Royal Challengers Bangalore
Chennai Super Kings Kolkata Knight Riders
Chennai Super Kings Rajasthan Royals
Chennai Super Kings Sunrisers Hyderabad
Delhi Capitals Kings XI Punjab
Delhi Capitals Royal Challengers Bangalore
Delhi Capitals Kolkata Knight Riders
Delhi Capitals Rajasthan Royals
Delhi Capitals Sunrisers Hyderabad
Kings XI Punjab Royal Challengers Bangalore
Kings XI Punjab Kolkata Knight Riders
Kings XI Punjab Rajasthan Royals
Kings XI Punjab Sunrisers Hyderabad
Kolkata Knight Riders Royal Challengers Bangalore
Rajasthan Royals Royal Challengers Bangalore
Royal Challengers Bangalore Sunrisers Hyderabad
Kolkata Knight Riders Rajasthan Royals
Kolkata Knight Riders Sunrisers Hyderabad
Rajasthan Royals Sunrisers Hyderabad
Chennai Super Kings Mumbai Indians
Delhi Capitals Mumbai Indians
Kings XI Punjab Mumbai Indians
Mumbai Indians Royal Challengers Bangalore
Kolkata Knight Riders Mumbai Indians
Mumbai Indians Rajasthan Royals
Mumbai Indians Sunrisers Hyderabad
Chennai Super Kings Delhi Capitals
Chennai Super Kings Kings XI Punjab
Chennai Super Kings Royal Challengers Bangalore
Chennai Super Kings Kolkata Knight Riders
Chennai Super Kings Rajasthan Royals
Chennai Super Kings Sunrisers Hyderabad
Delhi Capitals Kings XI Punjab
Delhi Capitals Royal Challengers Bangalore
Delhi Capitals Kolkata Knight Riders
Delhi Capitals Rajasthan Royals
Delhi Capitals Sunrisers Hyderabad
Kings XI Punjab Royal Challengers Bangalore
Kings XI Punjab Kolkata Knight Riders
Kings XI Punjab Rajasthan Royals
Kings XI Punjab Sunrisers Hyderabad
Kolkata Knight Riders Royal Challengers Bangalore
Rajasthan Royals Royal Challengers Bangalore
Royal Challengers Bangalore Sunrisers Hyderabad
Kolkata Knight Riders Rajasthan Royals
Kolkata Knight Riders Sunrisers Hyderabad
Rajasthan Royals Sunrisers Hyderabad

/Users/shailmirpuri/opt/anaconda3/lib/python3.8/site-packages/pandas/core/indexing.py:1637: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)

                             V1                           V2  V3
1           Chennai Super Kings               Mumbai Indians NaN
2                Delhi Capitals               Mumbai Indians NaN
3               Kings XI Punjab               Mumbai Indians NaN
4                Mumbai Indians  Royal Challengers Bangalore NaN
5         Kolkata Knight Riders               Mumbai Indians NaN
6                Mumbai Indians             Rajasthan Royals NaN
7                Mumbai Indians          Sunrisers Hyderabad NaN
8           Chennai Super Kings               Delhi Capitals NaN
9           Chennai Super Kings              Kings XI Punjab NaN
10          Chennai Super Kings  Royal Challengers Bangalore NaN
11          Chennai Super Kings        Kolkata Knight Riders NaN
12          Chennai Super Kings             Rajasthan Royals NaN
13          Chennai Super Kings          Sunrisers Hyderabad NaN
14               Delhi Capitals              Kings XI Punjab NaN
15               Delhi Capitals  Royal Challengers Bangalore NaN
16               Delhi Capitals        Kolkata Knight Riders NaN
17               Delhi Capitals             Rajasthan Royals NaN
18               Delhi Capitals          Sunrisers Hyderabad NaN
19              Kings XI Punjab  Royal Challengers Bangalore NaN
20              Kings XI Punjab        Kolkata Knight Riders NaN
21              Kings XI Punjab             Rajasthan Royals NaN
22              Kings XI Punjab          Sunrisers Hyderabad NaN
23        Kolkata Knight Riders  Royal Challengers Bangalore NaN
24             Rajasthan Royals  Royal Challengers Bangalore NaN
25  Royal Challengers Bangalore          Sunrisers Hyderabad NaN
26        Kolkata Knight Riders             Rajasthan Royals NaN
27        Kolkata Knight Riders          Sunrisers Hyderabad NaN
28             Rajasthan Royals          Sunrisers Hyderabad NaN
29          Chennai Super Kings               Mumbai Indians NaN
30               Delhi Capitals               Mumbai Indians NaN
31              Kings XI Punjab               Mumbai Indians NaN
32               Mumbai Indians  Royal Challengers Bangalore NaN
33        Kolkata Knight Riders               Mumbai Indians NaN
34               Mumbai Indians             Rajasthan Royals NaN
35               Mumbai Indians          Sunrisers Hyderabad NaN
36          Chennai Super Kings               Delhi Capitals NaN
37          Chennai Super Kings              Kings XI Punjab NaN
38          Chennai Super Kings  Royal Challengers Bangalore NaN
39          Chennai Super Kings        Kolkata Knight Riders NaN
40          Chennai Super Kings             Rajasthan Royals NaN
41          Chennai Super Kings          Sunrisers Hyderabad NaN
42               Delhi Capitals              Kings XI Punjab NaN
43               Delhi Capitals  Royal Challengers Bangalore NaN
44               Delhi Capitals        Kolkata Knight Riders NaN
45               Delhi Capitals             Rajasthan Royals NaN
46               Delhi Capitals          Sunrisers Hyderabad NaN
47              Kings XI Punjab  Royal Challengers Bangalore NaN
48              Kings XI Punjab        Kolkata Knight Riders NaN
49              Kings XI Punjab             Rajasthan Royals NaN
50              Kings XI Punjab          Sunrisers Hyderabad NaN
51        Kolkata Knight Riders  Royal Challengers Bangalore NaN
52             Rajasthan Royals  Royal Challengers Bangalore NaN
53  Royal Challengers Bangalore          Sunrisers Hyderabad NaN
54        Kolkata Knight Riders             Rajasthan Royals NaN
55        Kolkata Knight Riders          Sunrisers Hyderabad NaN
56             Rajasthan Royals          Sunrisers Hyderabad NaN

In [71]:
fix

,1WinPer,2WinPer,1H2H,BAT1_death,BAT1_pp,BAT1_mid,BOWL1_death,BOWL1_pp,BOWL1_mid,BAT2_death,BAT2_pp,BAT2_mid,BOWL2_death,BOWL2_pp,BOWL2_mid,h2hsco,h2hcon,h2hwtak,h2hwloss,h2hbhit,h2hbconced,1caught,1bowled,1lbw,1ro,2caught,2bowled,2lbw,2ro,1bat_avg,1bat_sr,1bowl_sr,1bowl_avg,2bat_avg,2bat_sr,2bowl_sr,2bowl_avg,WinA,WinB
1,0.574468,0.608696,0.250000,10.465779,7.053118,7.396304,9.784615,7.534247,7.450939,10.788293,7.984751,7.857041,9.269531,7.501767,7.602797,142.375000,152.375000,4.500000,7.125000,0.135714,0.168285,0.750000,0.083333,0.083333,0.027778,0.649123,0.052632,0.140351,0.035088,30.194175,1.277207,20.905830,27.627803,30.227451,1.355372,18.955645,24.512097,0.384615,0.615385
2,0.510638,0.608696,0.375000,9.974708,7.735849,7.786017,9.182257,8.220035,7.901879,10.788293,7.984751,7.857041,9.269531,7.501767,7.602797,160.125000,166.875000,5.875000,6.250000,0.160768,0.186096,0.680851,0.127660,0.063830,0.063830,0.620000,0.180000,0.080000,0.100000,28.085470,1.322600,18.704403,24.553459,30.227451,1.355372,18.955645,24.512097,0.384615,0.615385
3,0.428571,0.608696,0.333333,9.424865,8.038685,8.060086,10.769394,8.249047,7.781946,10.788293,7.984751,7.857041,9.269531,7.501767,7.602797,175.000000,183.833333,6.000000,5.166667,0.169583,0.198917,0.694444,0.166667,0.083333,0.055556,0.709677,0.161290,0.032258,0.064516,38.144068,1.374351,16.297872,23.957447,30.227451,1.355372,18.955645,24.512097,0.384615,0.615385
4,0.608696,0.418605,0.666667,10.788293,7.984751,7.857041,9.269531,7.501767,7.602797,10.224622,7.898496,7.455917,10.673751,7.815889,7.563707,182.000000,175.166667,6.000000,6.000000,0.189840,0.185889,0.750000,0.055556,0.027778,0.083333,0.694444,0.166667,0.055556,0.055556,30.227451,1.355372,18.955645,24.512097,31.514019,1.366842,22.622047,29.417323,0.307692,0.692308
5,0.500000,0.608696,0.166667,10.450844,7.908923,7.866962,10.267974,8.123699,8.177879,10.788293,7.984751,7.857041,9.269531,7.501767,7.602797,155.833333,177.833333,4.166667,6.500000,0.176230,0.209402,0.800000,0.040000,0.040000,0.040000,0.794872,0.051282,0.076923,0.051282,28.064935,1.346977,21.992908,30.489362,30.227451,1.355372,18.955645,24.512097,0.615385,0.384615
6,0.608696,0.418605,0.166667,10.788293,7.984751,7.857041,9.269531,7.501767,7.602797,9.548458,8.074873,7.641245,11.027027,8.005006,7.914388,178.500000,170.166667,5.500000,5.333333,0.178667,0.193687,0.696970,0.181818,0.060606,0.030303,0.687500,0.218750,0.031250,0.031250,30.227451,1.355372,18.955645,24.512097,28.622642,1.379718,21.397163,29.489362,0.384615,0.615385
7,0.608696,0.500000,0.500000,10.788293,7.984751,7.857041,9.269531,7.501767,7.602797,8.994152,8.110988,7.586020,9.335740,7.384615,7.301868,148.166667,142.000000,7.000000,7.166667,0.158184,0.143466,0.642857,0.190476,0.071429,0.047619,0.674419,0.139535,0.116279,0.023256,30.227451,1.355372,18.955645,24.512097,32.030303,1.278500,20.695906,25.099415,0.384615,0.615385
8,0.574468,0.510638,0.571429,10.465779,7.053118,7.396304,9.784615,7.534247,7.450939,9.974708,7.735849,7.786017,9.182257,8.220035,7.901879,161.285714,159.000000,6.142857,4.714286,0.163934,0.162515,0.604651,0.162791,0.093023,0.046512,0.757576,0.090909,0.030303,0.060606,30.194175,1.277207,20.905830,27.627803,28.085470,1.322600,18.704403,24.553459,0.307692,0.692308
9,0.574468,0.428571,0.666667,10.465779,7.053118,7.396304,9.784615,7.534247,7.450939,9.424865,8.038685,8.060086,10.769394,8.249047,7.781946,169.500000,165.333333,6.000000,3.166667,0.167813,0.162534,0.777778,0.166667,0.055556,0.000000,0.578947,0.263158,0.105263,0.052632,30.194175,1.277207,20.905830,27.627803,38.144068,1.374351,16.297872,23.957447,0.384615,0.615385
10,0.574468,0.418605,0.666667,10.465779,7.053118,7.396304,9.784615,7.534247,7.450939,10.224622,7.898496,7.455917,10.673751,7.815889,7.563707,141.333333,146.166667,7.333333,5.000000,0.139437,0.124829,0.681818,0.090909,0.000000,0.113636,0.533333,0.300000,0.000000,0.133333,30.194175,1.277207,20.905830,27.627803,31.514019,1.366842,22.622047,29.417323,0.307692,0.692308
11,0.574468,0.500000,0.666667,10.465779,7.053118,7.396304,9.784615,7.534247,7.450939,10.450844,7.908923,7.866962,10.267974,8.123699,8.177879,165.000000,165.000000,7.000000,4.500000,0.173370,0.181943,0.738095,0.071429,0.047619,0.095238,0.629630,0.222222,0.148148,0.000000,30.194175,1.277207,20.905830,27.627803,28.064935,1.346977,21.992908,30.489362,0.384615,0.615385
12,0.574468,0.418605,0.500000,10.465779,7.053118,7.396304,9.784615,7.534247,7.450939,9.548458,8.074873,7.641245,11.027027,8.005006,7.914388,172.500000,162.833333,6.833333,5.166667,0.162019,0.156727,0.682927,0.146341,0.048780,0.048780,0.677419,0.161290,0.000000,0.096774,30.194175,1.277207,20.905830,27.627803,28.622642,1.379718,21.397163,29.489362,0.307692,0.692308
13,0.574468,0.500000,0.750000,10.465779,7.053118,7.396304,9.784615,7.534247,7.450939,8.994152,8.110988,7.586020,9.335740,7.384615,7.301868,164.375000,162.125000,5.375000,4.375000,0.178980,0.155713,0.604651,0.093023,0.000000,0.093023,0.457143,0.228571,0.057143,0.142857,30.194175,1.277207,20.905830,27.627803,32.030303,1.278500,20.695906,25.099415,0.384615,0.615385
14,0.510638,0.428571,0.333333,9.974708,7.735849,7.786017,9.182257,8.220035,7.901879,9.424865,8.038685,8.060086,10.769394,8.249047,7.781946,157.333333,160.500000,6.833333,7.166667,0.145527,0.163912,0.658537,0.146341,0.048780,0.073171,0.511628,0.255814,0.069767,0.162791,28.085470,1.322600,18.704403,24.553459,38.144068,1.374351,16.297872,23.957447,0.384615,0.615385
15,0.510638,0.418605,0.666667,9.974708,7.735849,7.786017,9.182257,8.220035,7.901879,10.224622,7.898496,7.455917,10.673751,7.815889,7.563707,174.000000,162.000000,6.666667,4.666667,0.183060,0.153103,0.750000,0.125000,0.050000,0.050000,0.750000,0.178571,0.071429,0.000000,28.085470,1.322600,18.704403,24.553459,31.514019,1.366842,22.622047,29.417323,0.307692,0.692308
16,0.510638,0.500000,0.666667,9.974708,7.735849,7.786017,9.182257,8.220035,7.901879,10.450844,7.908923,7.866962,10.267974,8.123699,8.177879,179.333333,188.500000,7.833333,6.000000,0.207439,0.209396,0.659574,0.191489,0.042553,0.063830,0.666667,0.166667,0.055556,0.055556,28.085470,1.322600,18.704403,24.553459,28.064935,1.346977,21.992908,30.489362,0.384615,0.615385
17,0.510638,0.418605,0.833333,9.974708,7.735849,7.786017,9.182257,8.220035,7.901879,9.548458,8.074873,7.641245,11.027027,8.005006,7.914388,152.500000,148.500000,7.166667,5.666667,0.188312,0.156433,0.581395,0.232558,0.000000,0.116279,0.735294,0.058824,0.029412,0.088235,28.085470,1.322600,18.704403,24.553459,28.622642,1.379718,21.397163,29.489362,0.307692,0.692308
18,0.510638,0.500000,0.375000,9.974708,7.735849,7.786017,9.182257,8.220035,7.901879,8.994152,8.110988,7.586020,9.335740,7.384615,7.301868,158.250000,164.625000,5.125000,6.625000,0.152905,0.157895,0.731707,0.170732,0.048780,0.024390,0.641509,0.132075,0.113208,0.075472,28.085470,1.322600,18.704403,24.553459,32.030303,1.278500,20.695906,25.099415,0.384615,0.615385
19,0.428571,0.418605,0.333333,9.424865,8.038685,8.060086,10.769394,8.249047,7.781946,10.224622,7.898496,7.455917,10.673751,7.815889,7.563707,164.000000,151.166667,4.666667,6.000000,0.178121,0.178571,0.607143,0.285714,0.071429,0.035714,0.555556,0.166667,0.083333,0.111111,38.144068,1.374351,16.297872,23.957447,31.514019,1.366842,22.622047,29.417323,0.384615,0.615385
20,0.428571,0.500000,0.333333,9.424865,8.038685,8.060086,10.769394,8.249047,7.781946,10.450844,7.908923,7.866962,10.267974,8.123699,8.177879,170.833333,192.000000,5.833333,4.333333,0.204444,0.218453,0.685714,0.142857,0.028571,0.114286,0.692308,0.192308,0.076923,0.038462,38.144068,1.374351,16.297872,23.957447,28.064935,1.346977,21.992908,30.489362,0.615385,0.384615
21,0.428571,0.418605,0.500000,9.424865,8.038685,8.060086,10.769394,8.249047,7.781946,9.548458,8.074873,7.641245,11.027027,8.005006,7.914388,178.666667,177.000000,7.000000,4.500000,0.177658,0.178177,0.738095,0.095238,0.000000,0.119048,0.777778,0.148148,0.000000,0.037037,38.144068,1.374351,16.297872,23.957447,28.622642,1.379718,21.397163,29.489362,0.615385,0.384615
22,0.428571,0.500000,0.500000,9.424865,8.038685,8.060086,10.769394,8.249047,7.781946,8.994152,8.110988,7.586020,9.335740,7.384615,7.301868,148.000000,164.500000,6.166667,7.000000,0.137447,0.136605,0.702703,0.162162,0.027027,0.054054,0.595238,0.142857,0.119048,0.095238,38.144068,1.374351,16.297872,23.957447,32.030303,1.278500,20.695906,25.099415,0.384615,0.615385
23,0.500000,0.418605,0.500000,10.450844,7.908923,7.866962,10.267974,8.123699,8.177879,10.224622,7.898496,7.455917,10.673751,7.815889,7.563707,159.666667,174.666667,3.666667,6.333333,0.167794,0.192034,0.636364,0.227273,0.045455,0.045455,0.657895,0.184211,0.052632,0.078947,28.064935,1.346977,21.992908,30.489362,31.514019,1.366842,22.622047,29.417323,0.384615,0.615385
24,0.418605,0.418605,0.500000,9.548458,8.074873,7.641245,11.027027,8.005006,7.914388,10.224622,7.898496,7.455917,10.673751,7.815889,7.563707,152.833333,148.166667,5.333333,4.166667,0.171561,0.169014,0.656250,0.156250,0.031250,0.000000,0.720000,0.080000,0.120000,0.040000,28.622642,1.379718,21.397163,29.489362,31.514019,1.366842,22.622047,29.417323,0.307692,0.692308
25,0.418605,0.500000,0.428571,10.224622,7.898496,7.455917,10.673751,7.815889,7.563707,8.994152,8.110988,7.586020,9.335740,7.384615,7.301868,152.000000,166.000000,5.857143,6.714286,0.142526,0.173913,0.609756,0.195122,0.024390,0.121951,0.617021,0.170213,0.042553,0.127660,31.514019,1.366842,22.622047,29.417323,32.030303,1.278500,20.695906,25.099415,0.384615,0.615385
26,0.500000,0.418605,0.857143,10.450844,7.908923,7.866962,10.267974,8.123699,8.177879,9.548458,8.074873,7.641245,11.027027,8.005006,7.914388,165.285714,147.142857,7.142857,5.000000,0.194067,0.144706,0.620000,0.160000,0.060000,0.020000,0.685714,0.114286,0.028571,0.057143,28.064935,1.346977,21.992908,30.489362,28.622642,1.379718,21.397163,29.489362,0.307692,0.692308
27,0.500000,0.500000,0.571429,10.450844,7.908923,7.866962,10.267974,8.123699,8.177879,8.994152,8.110988,7.586020,9.335740,7.384615,7.301868,160.142857,161.714286,5.000000,6.000000,0.170414,0.158654,0.485714,0.228571,0.085714,0.114286,0.714286,0.142857,0.071429,0.047619,28.064935,1.346977,21.992908,30.489362,32.030303,1.278500,20.695906,25.099415,0.384615,0.615385
28,0.418605,0.500000,0.333333,9.548458,8.074873,7.641245,11.027027,8.005006,7.914388,8.994152,8.110988,7.586020,9.335740,7.384615,7.301868,156.833333,158.833333,4.500000,5.166667,0.139535,0.160229,0.703704,0.185185,0.037037,0.037037,0.612903,0.225806,0.032258,0.129032,28.622642,1.379718,21.397163,29.489362,32.030303,1.278500,20.695906,25.099415,0.384615,0.615385
29,0.574468,0.608696,0.250000,10.465779,7.053118,7.396304,9.784615,7.534247,7.450939,10.788293,7.984751,7.857041,9.269531,7.501767,7.602797,142.375000,152.375000,4.500000,7.125000,0.135714,0.168285,0.750000,0.083333,0.083333,0.027778,0.649123,0.052632,0.140351,0.035088,30.194175,1.277207,20.905830,27.627803,30.227451,1.355372,18.955645,24.512097,0.384615,0.615385
30,0.510638,0.608696,0.375000,9.974708,7.735849,7.786017,9.182257,8.220035,7.901879,10.788293,7.984751,7.857041,9.269531,7.501767,7.602797,160.125000,166.875000,5.875000,6.250000,0.160768,0.186096,0.680851,0.127660,0.063830,0.063830,0.620000,0.180000,0.080000,0.100000,28.085470,1.322600,18.704403,24.553459,30.227451,1.355372,18.955645,24.512097,0.384615,0.615385
31,0.428571,0.608696,0.333333,9.424865,8.038685,8.060086,10.769394,8.249047,7.781946,10.788293,7.984751,7.857041,9.269531,7.501767,7.602797,175.000000,183.833333,6.000000,5.166667,0.169583,0.198917,0.694444,0.166667,0.083333,0.055556,0.709677,0.161290,0.032258,0.064516,38.144068,1.374351,16.297872,23.957447,30.227451,1.355372,18.955645,24.512097,0.384615,0.615385
32,0.608696,0.418605,0.666667,10.788293,7.984751,7.857041,9.269531,7.501767,7.602797,10.224622,7.898496,7.455917,10.673751,7.815889,7.563707,182.000000,175.166667,6.000000,6.000000,0.189840,0.185889,0.750000,0.055556,0.027778,0.083333,0.694444,0.166667,0.055556,0.055556,30.227451,1.355372,18.955645,24.512097,31.514019,1.366842,22.622047,29.417323,0.307692,0.692308
33,0.500000,0.608696,0.166667,10.450844,7.908923,7.866962,10.267974,8.123699,8.177879,10.788293,7.984751,7.857041,9.269531,7.501767,7.602797,155.833333,177.833333,4.166667,6.500000,0.176230,0.209402,0.800000,0.040000,0.040000,0.040000,0.794872,0.051282,0.076923,0.051282,28.064935,1.346977,21.992908,30.489362,30.227451,1.355372,18.955645,24.512097,0.615385,0.384615
34,0.608696,0.418605,0.166667,10.788293,7.984751,7.857041,9.269531,7.501767,7.602797,9.548458,8.074873,7.641245,11.027027,8.005006,7.914388,178.500000,170.166667,5.500000,5.333333,0.178667,0.193687,0.696970,0.181818,0.060606,0.030303,0.687500,0.218750,0.031250,0.031250,30.227451,1.355372,18.955645,24.512097,28.622642,1.379718,21.397163,29.489362,0.384615,0.615385
35,0.608696,0.500000,0.500000,10.788293,7.984751,7.857041,9.269531,7.501767,7.602797,8.994152,8.110988,7.586020,9.335740,7.384615,7.301868,148.166667,142.000000,7.000000,7.166667,0.158184,0.143466,0.642857,0.190476,0.071429,0.047619,0.674419,0.139535,0.116279,0.023256,30.227451,1.355372,18.955645,24.512097,32.030303,1.278500,20.695906,25.099415,0.384615,0.615385
36,0.574468,0.510638,0.571429,10.465779,7.053118,7.396304,9.784615,7.534247,7.450939,9.974708,7.735849,7.786017,9.182257,8.220035,7.901879,161.285714,159.000000,6.142857,4.714286,0.163934,0.162515,0.604651,0.162791,0.093023,0.046512,0.757576,0.090909,0.030303,0.060606,30.194175,1.277207,20.905830,27.627803,28.085470,1.322600,18.704403,24.553459,0.307692,0.692308
37,0.574468,0.428571,0.666667,10.465779,7.053118,7.396304,9.784615,7.534247,7.450939,9.424865,8.038685,8.060086,10.769394,8.249047,7.781946,169.500000,165.333333,6.000000,3.166667,0.167813,0.162534,0.777778,0.166667,0.055556,0.000000,0.578947,0.263158,0.105263,0.052632,30.194175,1.277207,20.905830,27.627803,38.144068,1.374351,16.297872,23.957447,0.384615,0.615385
38,0.574468,0.418605,0.666667,10.465779,7.053118,7.396304,9.784615,7.534247,7.450939,10.224622,7.898496,7.455917,10.673751,7.815889,7.563707,141.333333,146.166667,7.333333,5.000000,0.139437,0.124829,0.681818,0.090909,0.000000,0.113636,0.533333,0.300000,0.000000,0.133333,30.194175,1.277207,20.905830,27.627803,31.514019,1.366842,22.622047,29.417323,0.307692,0.692308
39,0.574468,0.500000,0.666667,10.465779,7.053118,7.396304,9.784615,7.534247,7.450939,10.450844,7.908923,7.866962,10.267974,8.123699,8.177879,165.000000,165.000000,7.000000,4.500000,0.173370,0.181943,0.738095,0.071429,0.047619,0.095238,0.629630,0.222222,0.148148,0.000000,30.194175,1.277207,20.905830,27.627803,28.064935,1.346977,21.992908,30.489362,0.384615,0.615385
40,0.574468,0.418605,0.500000,10.465779,7.053118,7.396304,9.784615,7.534247,7.450939,9.548458,8.074873,7.641245,11.027027,8.005006,7.914388,172.500000,162.833333,6.833333,5.166667,0.162019,0.156727,0.682927,0.146341,0.048780,0.048780,0.677419,0.161290,0.000000,0.096774,30.194175,1.277207,20.905830,27.627803,28.622642,1.379718,21.397163,29.489362,0.307692,0.692308
41,0.574468,0.500000,0.750000,10.465779,7.053118,7.396304,9.784615,7.534247,7.450939,8.994152,8.110988,7.586020,9.335740,7.384615,7.301868,164.375000,162.125000,5.375000,4.375000,0.178980,0.155713,0.604651,0.093023,0.000000,0.093023,0.457143,0.228571,0.057143,0.142857,30.194175,1.277207,20.905830,27.627803,32.030303,1.278500,20.695906,25.099415,0.384615,0.615385
42,0.510638,0.428571,0.333333,9.974708,7.735849,7.786017,9.182257,8.220035,7.901879,9.424865,8.038685,8.060086,10.769394,8.249047,7.781946,157.333333,160.500000,6.833333,7.166667,0.145527,0.163912,0.658537,0.146341,0.048780,0.073171,0.511628,0.255814,0.069767,0.162791,28.085470,1.322600,18.704403,24.553459,38.144068,1.374351,16.297872,23.957447,0.384615,0.615385
43,0.510638,0.418605,0.666667,9.974708,7.735849,7.786017,9.182257,8.220035,7.901879,10.224622,7.898496,7.455917,10.673751,7.815889,7.563707,174.000000,162.000000,6.666667,4.666667,0.183060,0.153103,0.750000,0.125000,0.050000,0.050000,0.750000,0.178571,0.071429,0.000000,28.085470,1.322600,18.704403,24.553459,31.514019,1.366842,22.622047,29.417323,0.307692,0.692308
44,0.510638,0.500000,0.666667,9.974708,7.735849,7.786017,9.182257,8.220035,7.901879,10.450844,7.908923,7.866962,10.267974,8.123699,8.177879,179.333333,188.500000,7.833333,6.000000,0.207439,0.209396,0.659574,0.191489,0.042553,0.063830,0.666667,0.166667,0.055556,0.055556,28.085470,1.322600,18.704403,24.553459,28.064935,1.346977,21.992908,30.489362,0.384615,0.615385
45,0.510638,0.418605,0.833333,9.974708,7.735849,7.786017,9.182257,8.220035,7.901879,9.548458,8.074873,7.641245,11.027027,8.005006,7.914388,152.500000,148.500000,7.166667,5.666667,0.188312,0.156433,0.581395,0.232558,0.000000,0.116279,0.735294,0.058824,0.029412,0.088235,28.085470,1.322600,18.704403,24.553459,28.622642,1.379718,21.397163,29.489362,0.307692,0.692308
46,0.510638,0.500000,0.375000,9.974708,7.735849,7.786017,9.182257,8.220035,7.901879,8.994152,8.110988,7.586020,9.335740,7.384615,7.301868,158.250000,164.625000,5.125000,6.625000,0.152905,0.157895,0.731707,0.170732,0.048780,0.024390,0.641509,0.132075,0.113208,0.075472,28.085470,1.322600,18.704403,24.553459,32.030303,1.278500,20.695906,25.099415,0.384615,0.615385
47,0.428571,0.418605,0.333333,9.424865,8.038685,8.060086,10.769394,8.249047,7.781946,10.224622,7.898496,7.455917,10.673751,7.815889,7.563707,164.000000,151.166667,4.666667,6.000000,0.178121,0.178571,0.607143,0.285714,0.071429,0.035714,0.555556,0.166667,0.083333,0.111111,38.144068,1.374351,16.297872,23.957447,31.514019,1.366842,22.622047,29.417323,0.384615,0.615385
48,0.428571,0.500000,0.333333,9.424865,8.038685,8.060086,10.769394,8.249047,7.781946,10.450844,7.908923,7.866962,10.267974,8.123699,8.177879,170.833333,192.000000,5.833333,4.333333,0.204444,0.218453,0.685714,0.142857,0.028571,0.114286,0.692308,0.192308,0.076923,0.038462,38.144068,1.374351,16.297872,23.957447,28.064935,1.346977,21.992908,30.489362,0.615385,0.384615
49,0.428571,0.418605,0.500000,9.424865,8.038685,8.060086,10.769394,8.249047,7.781946,9.548458,8.074873,7.641245,11.027027,8.005006,7.914388,178.666667,177.000000,7.000000,4.500000,0.177658,0.178177,0.738095,0.095238,0.000000,0.119048,0.777778,0.148148,0.000000,0.037037,38.144068,1.374351,16.297872,23.957447,28.622642,1.379718,21.397163,29.489362,0.615385,0.384615
50,0.428571,0.500000,0.500000,9.424865,8.038685,8.060086,10.769394,8.249047,7.781946,8.994152,8.110988,7.586020,9.335740,7.384615,7.301868,148.000000,164.500000,6.166667,7.000000,0.137447,0.136605,0.702703,0.162162,0.027027,0.054054,0.595238,0.142857,0.119048,0.095238,38.144068,1.374351,16.297872,23.957447,32.030303,1.278500,20.695906,25.099415,0.384615,0.615385
51,0.500000,0.418605,0.500000,10.450844,7.908923,7.866962,10.267974,8.123699,8.177879,10.224622,7.898496,7.455917,10.673751,7.815889,7.563707,159.666667,174.666667,3.666667,6.333333,0.167794,0.192034,0.636364,0.227273,0.045455,0.045455,0.657895,0.184211,0.052632,0.078947,28.064935,1.346977,21.992908,30.489362,31.514019,1.366842,22.622047,29.417323,0.384615,0.615385
52,0.418605,0.418605,0.500000,9.548458,8.074873,7.641245,11.027027,8.005006,7.914388,10.224622,7.898496,7.455917,10.673751,7.815889,7.563707,152.833333,148.166667,5.333333,4.166667,0.171561,0.169014,0.656250,0.156250,0.031250,0.000000,0.720000,0.080000,0.120000,0.040000,28.622642,1.379718,21.397163,29.489362,31.514019,1.366842,22.622047,29.417323,0.307692,0.692308
53,0.418605,0.500000,0.428571,10.224622,7.898496,7.455917,10.673751,7.815889,7.563707,8.994152,8.110988,7.586020,9.335740,7.384615,7.301868,152.000000,166.000000,5.857143,6.714286,0.142526,0.173913,0.609756,0.195122,0.024390,0.121951,0.617021,0.170213,0.042553,0.127660,31.514019,1.366842,22.622047,29.417323,32.030303,1.278500,20.695906,25.099415,0.384615,0.615385

In [89]:
fixtures[['WinB', 'WinA']] = search.predict_proba(fix)
fixtures['V3'] = search.predict(fix)

In [91]:
for i in range(len(fixtures)):
    if fixtures['V3'].iloc[i] == 1:
        fixtures['V3'].iloc[i] = fixtures['V1'].iloc[i]
    else:
        fixtures['V3'].iloc[i] = fixtures['V2'].iloc[i]
fixtures

/Users/shailmirpuri/opt/anaconda3/lib/python3.8/site-packages/pandas/core/indexing.py:1637: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)

,V1,V2,V3,WinA,WinB
1,Chennai Super Kings,Mumbai Indians,Chennai Super Kings,0.615385,0.384615
2,Delhi Capitals,Mumbai Indians,Delhi Capitals,0.615385,0.384615
3,Kings XI Punjab,Mumbai Indians,Kings XI Punjab,0.615385,0.384615
4,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,0.692308,0.307692
5,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,0.384615,0.615385
6,Mumbai Indians,Rajasthan Royals,Mumbai Indians,0.615385,0.384615
7,Mumbai Indians,Sunrisers Hyderabad,Mumbai Indians,0.615385,0.384615
8,Chennai Super Kings,Delhi Capitals,Chennai Super Kings,0.692308,0.307692
9,Chennai Super Kings,Kings XI Punjab,Chennai Super Kings,0.615385,0.384615
10,Chennai Super Kings,Royal Challengers Bangalore,Chennai Super Kings,0.692308,0.307692
11,Chennai Super Kings,Kolkata Knight Riders,Chennai Super Kings,0.615385,0.384615
12,Chennai Super Kings,Rajasthan Royals,Chennai Super Kings,0.692308,0.307692
13,Chennai Super Kings,Sunrisers Hyderabad,Chennai Super Kings,0.615385,0.384615
14,Delhi Capitals,Kings XI Punjab,Delhi Capitals,0.615385,0.384615
15,Delhi Capitals,Royal Challengers Bangalore,Delhi Capitals,0.692308,0.307692
16,Delhi Capitals,Kolkata Knight Riders,Delhi Capitals,0.615385,0.384615
17,Delhi Capitals,Rajasthan Royals,Delhi Capitals,0.692308,0.307692
18,Delhi Capitals,Sunrisers Hyderabad,Delhi Capitals,0.615385,0.384615
19,Kings XI Punjab,Royal Challengers Bangalore,Kings XI Punjab,0.615385,0.384615
20,Kings XI Punjab,Kolkata Knight Riders,Kolkata Knight Riders,0.384615,0.615385
21,Kings XI Punjab,Rajasthan Royals,Rajasthan Royals,0.384615,0.615385
22,Kings XI Punjab,Sunrisers Hyderabad,Kings XI Punjab,0.615385,0.384615
23,Kolkata Knight Riders,Royal Challengers Bangalore,Kolkata Knight Riders,0.615385,0.384615
24,Rajasthan Royals,Royal Challengers Bangalore,Rajasthan Royals,0.692308,0.307692
25,Royal Challengers Bangalore,Sunrisers Hyderabad,Royal Challengers Bangalore,0.615385,0.384615
26,Kolkata Knight Riders,Rajasthan Royals,Kolkata Knight Riders,0.692308,0.307692
27,Kolkata Knight Riders,Sunrisers Hyderabad,Kolkata Knight Riders,0.615385,0.384615
28,Rajasthan Royals,Sunrisers Hyderabad,Rajasthan Royals,0.615385,0.384615
29,Chennai Super Kings,Mumbai Indians,Chennai Super Kings,0.615385,0.384615
30,Delhi Capitals,Mumbai Indians,Delhi Capitals,0.615385,0.384615
31,Kings XI Punjab,Mumbai Indians,Kings XI Punjab,0.615385,0.384615
32,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,0.692308,0.307692
33,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,0.384615,0.615385
34,Mumbai Indians,Rajasthan Royals,Mumbai Indians,0.615385,0.384615
35,Mumbai Indians,Sunrisers Hyderabad,Mumbai Indians,0.615385,0.384615
36,Chennai Super Kings,Delhi Capitals,Chennai Super Kings,0.692308,0.307692
37,Chennai Super Kings,Kings XI Punjab,Chennai Super Kings,0.615385,0.384615
38,Chennai Super Kings,Royal Challengers Bangalore,Chennai Super Kings,0.692308,0.307692
39,Chennai Super Kings,Kolkata Knight Riders,Chennai Super Kings,0.615385,0.384615
40,Chennai Super Kings,Rajasthan Royals,Chennai Super Kings,0.692308,0.307692
41,Chennai Super Kings,Sunrisers Hyderabad,Chennai Super Kings,0.615385,0.384615
42,Delhi Capitals,Kings XI Punjab,Delhi Capitals,0.615385,0.384615
43,Delhi Capitals,Royal Challengers Bangalore,Delhi Capitals,0.692308,0.307692
44,Delhi Capitals,Kolkata Knight Riders,Delhi Capitals,0.615385,0.384615
45,Delhi Capitals,Rajasthan Royals,Delhi Capitals,0.692308,0.307692
46,Delhi Capitals,Sunrisers Hyderabad,Delhi Capitals,0.615385,0.384615
47,Kings XI Punjab,Royal Challengers Bangalore,Kings XI Punjab,0.615385,0.384615
48,Kings XI Punjab,Kolkata Knight Riders,Kolkata Knight Riders,0.384615,0.615385
49,Kings XI Punjab,Rajasthan Royals,Rajasthan Royals,0.384615,0.615385
50,Kings XI Punjab,Sunrisers Hyderabad,Kings XI Punjab,0.615385,0.384615
51,Kolkata Knight Riders,Royal Challengers Bangalore,Kolkata Knight Riders,0.615385,0.384615
52,Rajasthan Royals,Royal Challengers Bangalore,Rajasthan Royals,0.692308,0.307692
53,Royal Challengers Bangalore,Sunrisers Hyderabad,Royal Challengers Bangalore,0.615385,0.384615
54,Kolkata Knight Riders,Rajasthan Royals,Kolkata Knight Riders,0.692308,0.307692
55,Kolkata Knight Riders,Sunrisers Hyderabad,Kolkata Knight Riders,0.615385,0.384615
56,Rajasthan Royals,Sunrisers Hyderabad,Rajasthan Royals,0.615385,0.384615

In [92]:
fixtures.to_csv('Model3FIX.csv')